package de.cas_ual_ty.dueldimension.clientutil;

import de.cas_ual_ty.dueldimension.DuelDimension;
import de.cas_ual_ty.dueldimension.card.properties.Properties;
import de.cas_ual_ty.dueldimension.duel.match.Banlist;
import net.minecraft.resources.ResourceLocation;

/**
 * Duel-screen textures, and card images at a resolution the screen actually
 * needs.
 * <p>
 * The board art is EDOPro's own (AGPL, see LICENSE.md beside the files). Card
 * art comes from the mod's image pipeline, but requested at an explicit size
 * rather than the {@code cardMainImageSize} config value — that setting exists
 * to keep item icons cheap and defaults to 64px, which is illegibly blurry
 * when a card is drawn large on a duel field or in a preview panel.
 */
public final class DuelTextures
{
    /**
     * The Master Rule 5 playmat. EDOPro keeps one mat per rules era and picks
     * by duel_field; field4 is the modern one, and the *-transparent variant
     * is only swapped in when a face-up Field Spell's own art is drawn
     * underneath it.
     */
    public static final ResourceLocation FIELD =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/field4.png");
    public static final ResourceLocation FIELD_TRANSPARENT =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/field-transparent4.png");
    /**
     * Card backs: EDOPro uses a different one per side (tCover[controler]), and
     * the pair is kept for that reason even though the player's chosen back
     * currently goes on both.
     * <p>
     * <b>Assigned, not computed, and that is deliberate.</b> A dozen call sites
     * across the duel screen ask {@code texture.equals(DuelTextures.COVER)} to
     * decide whether art is already card-shaped and should be drawn through the
     * full 0..1 UV range rather than the {@link #CARD_U0} letterbox window.
     * Those tests keep working precisely because they compare against whatever
     * the field holds <em>now</em>: the same field is the only producer of a
     * back, so producer and predicate cannot disagree. Turning either into a
     * method would break every one of them silently.
     * <p>
     * {@code volatile} because they are written from a settings button and read
     * from the render thread, which is the rule {@code DuelClientState} follows
     * for every static that crosses threads. A dropped {@code final} costs no
     * caller a recompile — an {@code ResourceLocation} is built by a method call, so
     * it was never a compile-time constant and was never inlined anywhere.
     *
     * @see CardBacks
     */
    // The anime back, matching CardBacks.ALL's first entry, which is the
    // default. These are overwritten the moment the stored choice is read --
    // but "the moment" is not zero, and a frame drawn before it showed the
    // other back. Two places naming one default is the cost of the field being
    // assigned rather than computed; the paragraph above is why it is.
    public static volatile ResourceLocation COVER =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/backs/anime.png");
    public static volatile ResourceLocation COVER_OPPONENT =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/backs/anime.png");

    /**
     * Prints both sides' cards on the given backs.
     * <p>
     * Two arguments although there is one choice today: {@link CardBacks} hands
     * the same texture twice, and a per-side choice is then a change to that
     * one call rather than to this shape.
     */
    public static void setCovers(ResourceLocation own, ResourceLocation opponent)
    {
        COVER = own;
        COVER_OPPONENT = opponent;
    }
    /**
     * The mute button's two states, side by side: cell 0 the speaker, cell 1
     * the speaker crossed out. A 256x256 sheet because that is the size every
     * widget texture here is and the one {@code DdBlitUtil} divides by.
     */
    public static final ResourceLocation MUSIC_ICONS =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/gui/duel/music.png");

    /** Fallback art for a card whose image is missing or still downloading. */
    public static final ResourceLocation UNKNOWN =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/unknown.png");
    /** The life-point bar frame; the fill inside it is drawn procedurally. */
    /**
     * The chain toggle's two links. White, so the HUD can tint it: lit while
     * chaining is automatic, dulled while it is manual. Generated by
     * {@code tools/make_chain_icon.py}.
     * <p>
     * <b>chain_toggle, not chain.</b> {@link #CHAIN} is the marker the board
     * puts on a card whose effect is chaining, and it already owned that
     * filename -- this overwrote it once. Two pictures, two names.
     */
    public static final ResourceLocation CHAIN_TOGGLE =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/chain_toggle.png");

    public static final ResourceLocation LP_FRAME =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/lpf.png");
    public static final ResourceLocation BACKDROP =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/bg.png");
    /** 5x4 atlas of 64px digits, used for chain-link and counter badges. */
    public static final ResourceLocation NUMBERS =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/number.png");


    /**
     * EDOPro's own forbidden/limited badges: 2x2 of 64px cells in a 128px file.
     * <p>
     * The reference client's {@code lim.png}, taken rather than drawn. These are
     * the marks a Yu-Gi-Oh! player already reads without being taught, and an
     * approximation of a symbol whose whole job is instant recognition would be
     * the wrong kind of original work.
     * <p>
     * The cells, read off the file: forbidden top-left, limited top-right,
     * semi-limited bottom-left. The fourth is a letter L, which EDOPro uses for
     * a marker this mod does not have a concept of; {@link #limitCell} does not
     * offer it rather than guessing what it would mean here.
     *
     * @see #limitCell for turning a banlist limit into a cell
     */
    public static final ResourceLocation LIMIT_BADGES =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/lim.png");

    /** One cell of {@link #LIMIT_BADGES} is half the file on each axis. */
    private static final float LIMIT_CELL = 0.5F;

    /**
     * Where a banlist limit's badge sits in {@link #LIMIT_BADGES}, or null.
     *
     * @param limit copies the list allows: 0 forbidden, 1 limited, 2 semi-limited
     * @return {@code {u0, v0, u1, v1}}, or null when the card is unrestricted
     *         and has no badge at all
     */
    public static float[] limitCell(int limit)
    {
        // Three, not four. A card the list does not mention is unlimited, and
        // Banlist.limitFor returns UNLIMITED for it -- so "no badge" is the
        // common answer and has to be an answer rather than a fall-through.
        if(limit < 0 || limit >= Banlist.UNLIMITED)
        {
            return null;
        }
        // Column then row, which is the order the file is laid out in: 0 and 1
        // across the top, 2 beginning the second row.
        float u0 = (limit % 2) * LIMIT_CELL;
        float v0 = (limit / 2) * LIMIT_CELL;
        return new float[] {u0, v0, u0 + LIMIT_CELL, v0 + LIMIT_CELL};
    }
    /**
     * A card square for the zones the playmat does not cover: the two extra
     * monster zones and the four piles. Drawn as a texture rather than as line
     * geometry so it goes through the same path as the mat and the cards.
     */
    public static final ResourceLocation SLOT =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/slot.png");
    /** The same square lit, for a zone the core is currently offering. */
    public static final ResourceLocation SLOT_ACTIVE =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/slot_active.png");
    /**
     * The side of a card stack: 16x2, a white row over a gray row, tiled
     * vertically once per card so a pile's edge reads as many thin cards.
     */
    public static final ResourceLocation STACK_SIDE =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/stackside.png");
    /**
     * Plain white, for tinted screen-space shapes (the attack line). Flat
     * colour geometry has to go through the textured path here: the
     * position_color path has never rendered on this screen.
     */
    public static final ResourceLocation WHITE =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/white.png");
    /**
     * The phase indicator, as plain PNGs so the art can be repainted without
     * touching code. The case is a slim chrome housing with six bays; each
     * atlas is six columns by two rows -- the top row idle, the bottom row lit
     * with glowing letters for the current phase. Blue is used on your turn,
     * red on the opponent's.
     */
    public static final ResourceLocation PHASE_CASE =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/phase_case.png");
    public static final ResourceLocation PHASE_BLUE =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/phase_blue.png");
    public static final ResourceLocation PHASE_RED =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/phase_red.png");
    /**
     * The coin, as two frames side by side: tails on the left, heads on the
     * right. Replaceable art -- drop a new file here and the flip uses it.
     */
    public static final ResourceLocation COIN =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/coin.png");
    /**
     * The marks on the two Spell/Trap zones that are also Pendulum Zones.
     * <p>
     * Under MR5 -- which is the mode every duel here runs -- ocgcore sets
     * DUEL_PZONE without DUEL_SEPARATE_PZONE, so a scale occupies backrow zone
     * 0 or 4 rather than a zone of its own. Nothing on the playmat says which
     * two those are, so the zones say it.
     * <p>
     * One colour per zone, not both on both: blue is the left scale and red
     * the right, the way a Pendulum card prints them.
     */
    /**
     * The two colours a Pendulum card prints its scales in: blue on the left,
     * red on the right.
     * <p>
     * Opaque, with the alpha left to the caller -- the world board fades its
     * whole mat at the end of a duel and the flat screen does not.
     */
    public static final int PENDULUM_BLUE = 0xFF5698E0;
    public static final int PENDULUM_RED = 0xFFD65852;

    public static final ResourceLocation PENDULUM_ZONE_LEFT = ResourceLocation.fromNamespaceAndPath(
        DuelDimension.MOD_ID, "textures/duel/pendulum_zone_left.png");
    public static final ResourceLocation PENDULUM_ZONE_RIGHT = ResourceLocation.fromNamespaceAndPath(
        DuelDimension.MOD_ID, "textures/duel/pendulum_zone_right.png");

    /** The field spell zone's own square, marked with a compass rose. */
    public static final ResourceLocation FIELD_SPELL =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/field_spell.png");
    /**
     * Digits 0-9 in the reference's stack-indicator style: bold, white, heavily
     * outlined. EDOPro's own number.png carries whole numbers 1 to 20 with no
     * zero, so it cannot spell an arbitrary pile count; this matches its look
     * while composing.
     */
    /**
     * The plate the turn number stands on, at the middle of the board.
     * <p>
     * White art, tinted at the draw: green while the turn is yours and red
     * while it is not, which is the pair {@code DuelHud} owns. Generated by
     * {@code tools/make_turn_badge.py}.
     */
    public static final ResourceLocation TURN_BADGE =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/turn_badge.png");

    public static final ResourceLocation DIGITS =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/digits.png");
    /**
     * EDOPro's own equip mark, laid over the partner of a hovered equip card
     * ({@code drawing.cpp}:404, {@code imageManager.tEquip}).
     */
    public static final ResourceLocation EQUIP =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/equip.png");
    public static final ResourceLocation ACT =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/act.png");
    public static final ResourceLocation ATTACK =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/attack.png");
    public static final ResourceLocation CHAIN =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/chain.png");
    public static final ResourceLocation NEGATED =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/negated.png");
    public static final ResourceLocation TARGET =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/target.png");

    /**
     * Cards drawn on the field.
     * <p>
     * A card on the table is perhaps 70 screen pixels wide, but Minecraft's GUI
     * scale multiplies that by up to 4 on a large display, and the perspective
     * enlarges the near row further. 512 keeps the art sharp at those sizes and
     * costs one 1&nbsp;MB texture per distinct card in the duel.
     * <p>
     * The preview deliberately requests the same size: the pipeline caches one
     * file per (card, size), so sharing the number means the field and the
     * preview share a single texture instead of generating two.
     */
    public static final int FIELD_CARD_SIZE = 512;
    /** The preview panel draws a card several hundred pixels tall. */
    public static final int PREVIEW_CARD_SIZE = 512;

    /**
     * The size card icons are fetched at in the deck editor's grids.
     * <p>
     * Twice the 64 the rest of the mod uses for its "main" images, and drawn at
     * the same size on screen: the grids show a card at around forty pixels
     * across, and a 64-pixel source has barely more detail than that to give.
     * Fetching at 128 and letting the GPU scale it down costs a little memory
     * and makes the art legible.
     */
    public static final int ICON_CARD_SIZE = 128;

    /** EDOPro's cover.png is 480x700; keep that ratio wherever we draw a card. */
    public static final float CARD_ASPECT = 480F / 700F;

    /**
     * The mod stores card images letterboxed inside a square: measured across
     * every cached image, the card occupies u 0.199..0.801 and v 0.0625..0.9375
     * (aspect 0.6875, matching the printed card). Drawing the whole square into
     * a card-shaped quad squeezes the art; sampling this window instead keeps
     * it true. EDOPro's own textures (cover, unknown) are already card-shaped
     * and use the full range.
     */
    public static final float CARD_U0 = 0.19922F;
    public static final float CARD_U1 = 0.80078F;
    public static final float CARD_V0 = 0.0625F;
    public static final float CARD_V1 = 0.9375F;

    /**
     * The mod already ships an icon per duel action for its manual mode;
     * reusing them gives the command menu a symbol beside every entry.
     * Reposition has two icons because the action differs by current position.
     */
    public static ResourceLocation commandIcon(int command, boolean faceDown, boolean attackPosition)
    {
        // THE NDS GAME'S OWN BUTTONS, not the mod's own icons and not EDOPro's.
        //
        // World Championship 2011 answers a selected card with a row of picture
        // buttons, and these are those pictures -- extracted from `duel2d.pac`,
        // documented in `textures/gui/duel/cmd/CREDITS.md` beside them. EDOPro
        // has no art to take here at all: its menu is text (ShowMenu builds
        // plain buttons), which is why this used to be a mixture of two of its
        // field markers and nine icons drawn for this mod.
        //
        // Each file is 32x64 -- two states, idle over selected. Sampling is the
        // caller's job through `COMMAND_ICON_*`; this only says which file.
        //
        // The two REPOS captions are two different buttons in the original, and
        // that is the one place a command maps to more than one picture: a card
        // that would go to attack shows the upright card, one that would go to
        // defence shows it lying down. Measured off the icons rather than
        // assumed -- see the vault note.
        String name = switch(command)
        {
            case de.cas_ual_ty.dueldimension.ocg.prompt.CardCommands.COMMAND_ACTIVATE -> "activate";
            case de.cas_ual_ty.dueldimension.ocg.prompt.CardCommands.COMMAND_SUMMON -> "summon";
            case de.cas_ual_ty.dueldimension.ocg.prompt.CardCommands.COMMAND_SPSUMMON -> "special_summon";
            case de.cas_ual_ty.dueldimension.ocg.prompt.CardCommands.COMMAND_MSET -> "set_monster";
            case de.cas_ual_ty.dueldimension.ocg.prompt.CardCommands.COMMAND_SSET -> "set_spell";
            // A face-down card flipping up is the flip-summon button; a face-up
            // one is changing posture, and which way decides the picture.
            case de.cas_ual_ty.dueldimension.ocg.prompt.CardCommands.COMMAND_REPOS ->
                faceDown ? "flip_summon" : attackPosition ? "to_defence" : "to_attack";
            case de.cas_ual_ty.dueldimension.ocg.prompt.CardCommands.COMMAND_ATTACK -> "attack";
            case de.cas_ual_ty.dueldimension.ocg.prompt.CardCommands.COMMAND_LIST -> "list";
            default -> null;
        };
        return name == null ? null
            : ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID,
                "textures/gui/duel/cmd/" + name + ".png");
    }

    /**
     * The v range of one state in a {@link #commandIcon} file.
     * <p>
     * They are 32x64: idle on top, selected underneath. The ROM stores them the
     * other way round and `duel_buttons.py` flips them on the way out, so that
     * row 0 is idle here as it is in every other state atlas the mod draws.
     */
    public static final float COMMAND_ICON_IDLE_V0 = 0F;
    public static final float COMMAND_ICON_IDLE_V1 = 0.5F;
    public static final float COMMAND_ICON_SELECTED_V0 = 0.5F;
    public static final float COMMAND_ICON_SELECTED_V1 = 1F;

    private DuelTextures()
    {
    }

    /**
     * The artwork index a duel wire value asks for, as an index this card
     * actually has.
     * <p>
     * A duel carries the artwork chosen for a copy as a plain int, and it
     * arrives from a deck that may have been built when the card had more
     * artwork than the database now lists. {@code adjustImageIndex} already
     * folds an index the card does not have back to the printed one; this adds
     * the range check that has to happen before the narrowing to byte, because
     * an int of 256 would otherwise become the perfectly valid byte 0 by
     * accident rather than by decision, and one of 200 a negative.
     */
    public static byte artIndex(Properties properties, int art)
    {
        if(art <= 0 || art > Byte.MAX_VALUE)
        {
            return 0;
        }
        return properties.adjustImageIndex((byte)art);
    }

    /**
     * A card image at an explicit size. Requesting a size the pipeline has not
     * produced yet kicks off its generation and yields a placeholder in the
     * meantime, exactly as the rest of the mod behaves.
     */
    public static ResourceLocation card(Properties properties, byte imageIndex, int size)
    {
        return card(properties, imageIndex, size, false);
    }

    /**
     * The same cached card PNG through the resource pack's bilinear path.
     * A separate identifier matters: samplers belong to loaded textures in
     * 26.2, not to individual draws, so this keeps field cards crisp while a
     * heavily downscaled preview uses linear minification.
     */
    public static ResourceLocation cardSmooth(Properties properties, byte imageIndex, int size)
    {
        return card(properties, imageIndex, size, true);
    }

    // There is no cardUnowned. An unowned card is the SAME image as an owned
    // one, greyed by the draw -- see UnownedPipelines -- so ownership is an
    // argument the three call sites pass to their blit rather than a third
    // identifier over the same file. That identifier cost a second, CPU-built
    // copy of every unowned card's PNG, and a card shown greyed in a grid and
    // owned in a preview cost two decodes and two resident textures instead of
    // one.

    /**
     * A sealed product's icon, through the resource pack's bilinear path.
     * <p>
     * <b>Set icons had no smooth path at all, and almost none of them were
     * filtered.</b> Cards get one because every preview call site asks for
     * {@link #cardSmooth}; a set icon was only ever addressed as
     * {@code textures/item/<size>/<name>.png}, which {@link DdCardResourcePack}
     * serves with no metadata whatsoever — so a 512-pixel product icon drawn
     * into a 30-pixel shop tile kept one pixel in seventeen. The 299 icons the
     * mod ships were the exception, because {@code tools/add_texture_blur.py}
     * wrote them a real {@code .mcmeta}; the ~950 downloaded ones have none,
     * which is why some tiles looked smooth and most did not.
     * <p>
     * The prefix is chosen rather than fixed, because the two halves reach
     * bilinear by different routes:
     * <ul>
     * <li>a SHIPPED icon carries its own {@code .mcmeta} on disk, and the
     *     smooth prefix could not serve it anyway — that prefix resolves only
     *     through the image cache, which a bundled icon is not in;</li>
     * <li>a DOWNLOADED icon has no metadata on disk, and the smooth prefix is
     *     the only thing that gives it any.</li>
     * </ul>
     * The condition is {@link ImageHandler#getReplacementImage(CardSet, int)}'s
     * own, so the two cannot disagree about which branch an icon is on.
     */
    public static ResourceLocation setIconSmooth(de.cas_ual_ty.dueldimension.set.CardSet set)
    {
        String image = DuelDimension.proxy.getSetInfoReplacementImage(set);
        // Still fetching, or gave up. Those two names carry no size and no
        // cached file, so the smooth prefix has nothing to serve them from --
        // asking for one would turn a placeholder into a missing texture.
        if(image.endsWith("set_loading") || image.endsWith("set_failed"))
        {
            return ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID,
                DdCardResourcePack.PATH_PREFIX + image + ".png");
        }
        boolean shipped = set.getIsHardcoded() || ImageHandler.hasBundledImage(image);
        return ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID,
            (shipped ? DdCardResourcePack.PATH_PREFIX : DdCardResourcePack.SMOOTH_PATH_PREFIX)
                + image + ".png");
    }

    private static ResourceLocation card(Properties properties, byte imageIndex, int size, boolean smooth)
    {
        String image = ImageHandler.getReplacementImage(properties, imageIndex, size);
        // While the pipeline is still fetching (or gave up on) a card, show
        // the reference client's own "unknown card" art rather than the mod's
        // loading placeholder, which reads as a broken card on a duel field.
        if(image.endsWith("card_loading") || image.endsWith("card_failed"))
        {
            return UNKNOWN;
        }
        ResourceLocation __id = ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID,
            (smooth ? DdCardResourcePack.SMOOTH_PATH_PREFIX : DdCardResourcePack.PATH_PREFIX)
                + image + ".png");
        // Through the manager, never straight to the caller. An ResourceLocation that
        // reaches a blit before the manager has registered a texture under it
        // is read, decoded and uploaded inline on the render thread, which is
        // the hitch; the manager hands back the placeholder instead and a
        // worker has the art ready a frame or two later. It is also what makes
        // the texture releasable -- see CardTextureCache.
        return CardImageManager.getTextureCard(__id, size);
    }



}
