package de.cas_ual_ty.dueldimension.clientutil.hub;

import de.cas_ual_ty.dueldimension.DuelDimension;
import net.minecraft.resources.Identifier;

/** The hub's furniture, all of it PNG. Generated by {@code tools/gen_hub_ui.py}. */
public final class HubTextures
{
    private static Identifier gui(String path)
    {
        return Identifier.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/gui/" + path);
    }

    /** Nine-slice container, raised. */
    public static final Identifier PANEL = gui("common/panel.png");
    /** Nine-slice container, recessed: lists and fields sit in these. */
    public static final Identifier PANEL_INSET = gui("common/panel_inset.png");
    /** Three rows: idle, hovered, disabled. */
    public static final Identifier BUTTON = gui("common/button.png");
    /** Three rows: idle, hovered, selected. */
    public static final Identifier TAB = gui("common/tab.png");
    /** A single card slot for the deck editor grids. */
    public static final Identifier SLOT = gui("common/slot.png");

    /** Section header for the editor's grids. */
    public static final Identifier HEADER = gui("deckeditor/header.png");
    /** The dark band the open deck's name sits in, above the grids. */
    public static final Identifier TITLE_RIBBON = gui("deckeditor/title_ribbon.png");
    /** Marks a favourited card, drawn in the corner of its icon. */
    public static final Identifier STAR = gui("deckeditor/star.png");
    /** The recessed search field the trunk is filtered with. */
    public static final Identifier SEARCH_FIELD = gui("deckeditor/search_field.png");
    /** Filter chip; three rows, the third being lit rather than disabled. */
    public static final Identifier CHIP = gui("deckeditor/chip.png");
    /** Two tiles: track then thumb. */
    public static final Identifier SCROLLBAR = gui("deckeditor/scrollbar.png");

    /** Hue around, saturation outward; the picker samples it directly. */
    public static final Identifier COLOUR_WHEEL = gui("settings/colour_wheel.png");
    /** The brightness the wheel does not carry. */
    public static final Identifier VALUE_SLIDER = gui("settings/value_slider.png");
    /** The ring marking the chosen point. */
    public static final Identifier PICKER_CURSOR = gui("settings/picker_cursor.png");

    /**
     * The neutral mat. Carries the mat's lightness and none of its hue, so
     * multiplying it by a chosen colour gives that colour rather than a blend.
     */
    public static final Identifier CUSTOM_MAT =
        Identifier.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/mats/custom.png");

    private HubTextures()
    {
    }
}
