package de.cas_ual_ty.dueldimension.clientutil.hub;

import de.cas_ual_ty.dueldimension.DuelDimension;
import net.minecraft.resources.ResourceLocation;

/** The hub's furniture, all of it PNG. Generated by {@code tools/gen_hub_ui.py}. */
public final class HubTextures
{
    private static ResourceLocation gui(String path)
    {
        return new ResourceLocation(DuelDimension.MOD_ID, "textures/gui/" + path);
    }

    /** Nine-slice container, raised. */
    public static final ResourceLocation PANEL = gui("common/panel.png");
    /** Nine-slice container, recessed: lists and fields sit in these. */
    public static final ResourceLocation PANEL_INSET = gui("common/panel_inset.png");
    /** Three rows: idle, hovered, disabled. */
    public static final ResourceLocation BUTTON = gui("common/button.png");
    /** Three rows: idle, hovered, selected. */
    public static final ResourceLocation TAB = gui("common/tab.png");
    /** A single card slot for the deck editor grids. */
    public static final ResourceLocation SLOT = gui("common/slot.png");

    /** Section header for the editor's grids. */
    public static final ResourceLocation HEADER = gui("deckeditor/header.png");
    /** The recessed search field the trunk is filtered with. */
    public static final ResourceLocation SEARCH_FIELD = gui("deckeditor/search_field.png");
    /** Filter chip; three rows, the third being lit rather than disabled. */
    public static final ResourceLocation CHIP = gui("deckeditor/chip.png");
    /** Two tiles: track then thumb. */
    public static final ResourceLocation SCROLLBAR = gui("deckeditor/scrollbar.png");

    /** The shopkeeper portrait. Replaceable art: drop a PNG here and it is used. */
    public static final ResourceLocation SHOPKEEPER = gui("shop/shopkeeper.png");

    /** Hue around, saturation outward; the picker samples it directly. */
    public static final ResourceLocation COLOUR_WHEEL = gui("settings/colour_wheel.png");
    /** The brightness the wheel does not carry. */
    public static final ResourceLocation VALUE_SLIDER = gui("settings/value_slider.png");
    /** The ring marking the chosen point. */
    public static final ResourceLocation PICKER_CURSOR = gui("settings/picker_cursor.png");

    /**
     * The neutral mat. Carries the mat's lightness and none of its hue, so
     * multiplying it by a chosen colour gives that colour rather than a blend.
     */
    public static final ResourceLocation CUSTOM_MAT =
        new ResourceLocation(DuelDimension.MOD_ID, "textures/duel/mats/custom.png");

    private HubTextures()
    {
    }
}
