package de.cas_ual_ty.dueldimension.clientutil.hub;

import de.cas_ual_ty.dueldimension.DuelDimension;
import net.minecraft.resources.Identifier;

/** The hub's furniture, all of it PNG. Generated by {@code tools/gen_hub_ui.py}. */
public final class HubTextures
{
    private static Identifier gui(String path)
    {
        return Identifier.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/gui/" + path);
    }

    /** Nine-slice container, raised. */
    public static final Identifier PANEL = gui("common/panel.png");
    /** Nine-slice container, recessed: lists and fields sit in these. */
    public static final Identifier PANEL_INSET = gui("common/panel_inset.png");
    /** Three rows: idle, hovered, disabled. */
    public static final Identifier BUTTON = gui("common/button.png");
    /** Three rows: idle, hovered, selected. */
    public static final Identifier TAB = gui("common/tab.png");
    /** A single card slot for the deck editor grids. */
    public static final Identifier SLOT = gui("common/slot.png");
    /**
     * A tick, white so it can be tinted to whatever the label beside it would
     * have been. Drawn by {@link HubWidgets.IconButton}.
     */
    public static final Identifier CHECK = gui("common/check.png");

    /** Fixed-ratio Master Duel deck tile, without its interaction outline. */
    public static final Identifier DECK_TILE = gui("hub/deck_tile_surface.png");
    /** The active deck's rank plate, already clipped to the tile silhouette. */
    public static final Identifier DECK_TILE_SELECTED = gui("hub/deck_tile_selected.png");
    /** Three full-size rows: idle, hovered and active deck outlines. */
    public static final Identifier DECK_TILE_FRAME = gui("hub/deck_tile_frame.png");
    /** Temporary deck case used until deck-specific cases are part of profile data. */
    public static final Identifier DECK_PLACEHOLDER = gui("hub/deck_placeholder.png");
    public static final Identifier DECK_BOX_RED = gui("hub/deck_box_red.png");
    public static final Identifier DECK_BOX_PURPLE = gui("hub/deck_box_purple.png");
    public static final Identifier DECK_BOX_VORTEX_OF_MAGIC =
        gui("hub/deck_box_vortex_of_magic.png");
    public static final Identifier DECK_BOX_BLUE_EYES_MAX =
        gui("hub/deck_box_blue_eyes_max.png");
    public static final Identifier DECK_BOX_DARK_MAGICAL_BLAST =
        gui("hub/deck_box_dark_magical_blast.png");
    public static final Identifier DECK_BOX_RAGE_OF_DEEP_BLUE =
        gui("hub/deck_box_rage_of_deep_blue.png");
    public static final Identifier DECK_BOX_CYBER_KAISER =
        gui("hub/deck_box_cyber_kaiser.png");
    public static final Identifier DECK_BOX_MILLENNIUM_PUZZLE =
        gui("hub/deck_box_millennium_puzzle.png");
    /** Master Duel's add-deck glyph. */
    public static final Identifier ADD_DECK = gui("hub/add_deck.png");
    /** Regulation ring; the word inside remains normal rendered text. */
    public static final Identifier STANDARD_BADGE = gui("hub/standard_badge.png");

    public static Identifier deckBox(
        de.cas_ual_ty.dueldimension.duel.profile.DeckBoxStyle style)
    {
        return switch(style == null
            ? de.cas_ual_ty.dueldimension.duel.profile.DeckBoxStyle.BLUE : style)
        {
            case RED -> DECK_BOX_RED;
            case PURPLE -> DECK_BOX_PURPLE;
            case VORTEX_OF_MAGIC -> DECK_BOX_VORTEX_OF_MAGIC;
            case BLUE_EYES_MAX -> DECK_BOX_BLUE_EYES_MAX;
            case DARK_MAGICAL_BLAST -> DECK_BOX_DARK_MAGICAL_BLAST;
            case RAGE_OF_DEEP_BLUE -> DECK_BOX_RAGE_OF_DEEP_BLUE;
            case CYBER_KAISER -> DECK_BOX_CYBER_KAISER;
            case THE_MILLENNIUM_PUZZLE -> DECK_BOX_MILLENNIUM_PUZZLE;
            case BLUE -> DECK_PLACEHOLDER;
        };
    }

    /** Section header for the editor's grids. */
    public static final Identifier HEADER = gui("deckeditor/header.png");
    /** The dark band the open deck's name sits in, above the grids. */
    public static final Identifier TITLE_RIBBON = gui("deckeditor/title_ribbon.png");
    /** Marks a favourited card, drawn in the corner of its icon. */
    public static final Identifier STAR = gui("deckeditor/star.png");
    /**
     * Marks a card that has more than one artwork, drawn in the corner of its
     * icon. Shares that corner with {@link #STAR}, which moves aside for it.
     */
    public static final Identifier ALT_ART = gui("deckeditor/alt_art.png");
    /** The recessed search field the trunk is filtered with. */
    public static final Identifier SEARCH_FIELD = gui("deckeditor/search_field.png");
    /** Filter chip; three rows, the third being lit rather than disabled. */
    public static final Identifier CHIP = gui("deckeditor/chip.png");
    /** Two tiles: track then thumb. */
    public static final Identifier SCROLLBAR = gui("deckeditor/scrollbar.png");

    /** Hue around, saturation outward; the picker samples it directly. */
    public static final Identifier COLOUR_WHEEL = gui("settings/colour_wheel.png");
    /** The brightness the wheel does not carry. */
    public static final Identifier VALUE_SLIDER = gui("settings/value_slider.png");
    /** The ring marking the chosen point. */
    public static final Identifier PICKER_CURSOR = gui("settings/picker_cursor.png");

    /**
     * The neutral mat. Carries the mat's lightness and none of its hue, so
     * multiplying it by a chosen colour gives that colour rather than a blend.
     */
    public static final Identifier CUSTOM_MAT =
        Identifier.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/mats/custom.png");

    private HubTextures()
    {
    }
}
