package de.cas_ual_ty.dueldimension.card;

import de.cas_ual_ty.dueldimension.DuelDimension;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.Item;

public enum CardSleevesType
{
    // The plain card back: no sleeve at all, and what a deck falls back
    // to when its saved sleeve is one this build does not have. See
    // Sleeves.CODEC.
    CARD_BACK("card_back", 0x9F5F24),

    // Master Duel's protector catalogue, by its own item ids and its own
    // English names. Generated by tools/import_sleeves.py -- add sleeves
    // by re-running that, not by hand.
    //
    // Appended in id order and never re-ordered, because index == ordinal
    // (see the static block below) and that index is what
    // InitSleevesAction puts on the wire. Nothing on DISK stores an index:
    // Sleeves writes the name, precisely so this list can grow.
    AURAM_THE_WORLD_CHALICE_BLADEMASTER("auram_the_world_chalice_blademaster", 0x4D6F8A),   // 1070002
    LINK_BLACK("link_black", 0x4E4F4C),   // 1070003
    FUSION_PURPLE("fusion_purple", 0x633E85),   // 1070004
    SYNCHRO_SILVER("synchro_silver", 0x9DBCD4),   // 1070005
    XYZ_BLACK("xyz_black", 0x284855),   // 1070006
    GEARTOWN("geartown", 0x85825B),   // 1070007
    ASH_BLOSSOM_JOYOUS_SPRING("ash_blossom_joyous_spring", 0xA58479),   // 1070008
    BLUE_EYES_CHAOS_MAX_DRAGON("blue_eyes_chaos_max_dragon", 0x5B829C),   // 1070009
    TRISHULA_DRAGON_OF_THE_ICE_BARRIER("trishula_dragon_of_the_ice_barrier", 0x454E6B),   // 1070010
    PROTECTOR_SILVER("protector_silver", 0xB19E5A),   // 1070011
    DRAGONMAID_SEND_OFF("dragonmaid_send_off", 0xA87B5B),   // 1070012
    PROTECTOR_FIRE("protector_fire", 0xC2201E),   // 1070013
    PROTECTOR_WIND("protector_wind", 0x13843E),   // 1070014
    PROTECTOR_WATER("protector_water", 0x317DB5),   // 1070015
    PROTECTOR_EARTH("protector_earth", 0x914C1F),   // 1070016
    PROTECTOR_LIGHT("protector_light", 0xE5C850),   // 1070017
    PROTECTOR_DARK("protector_dark", 0x962883),   // 1070018
    TOKEN_COLLECTOR("token_collector", 0xB6B744),   // 1070019
    LINK_BLUE("link_blue", 0x3E71AB),   // 1070020
    DC_2022_AUG_CELEBRATION("dc_2022_aug_celebration", 0x23124F),   // 1070021
    GHOSTRICK_FESTIVAL("ghostrick_festival", 0x4D458E),   // 1070022
    DINOMORPHIA_FRENZY("dinomorphia_frenzy", 0xB54B3C),   // 1070023
    RUNICK_FOUNTAIN("runick_fountain", 0x5D9CC0),   // 1070024
    LOVELY_LABRYNTH_OF_THE_SILVER_CASTLE("lovely_labrynth_of_the_silver_castle", 0x6D9BBF),   // 1070025
    MAMONAKA_THE_VAYLANTZ_UNITED("mamonaka_the_vaylantz_united", 0x6C88B5),   // 1070026
    THERION_KING_REGULUS("therion_king_regulus", 0xB45F3E),   // 1070027
    TRI_BRIGADE("tri_brigade", 0x8D6455),   // 1070028
    THE_WEATHER_FORECAST("the_weather_forecast", 0x6B81A2),   // 1070029
    DC_2022_DEC_CELEBRATION("dc_2022_dec_celebration", 0x241351),   // 1070030
    THE_MILLENNIUM_PUZZLE("the_millennium_puzzle", 0x0F0707),   // 1070031
    THE_WORLD_LEGACY("the_world_legacy", 0x327BB1),   // 1070032
    VERA_THE_VERNUSYLPH_GODDESS("vera_the_vernusylph_goddess", 0x86D3D9),   // 1070033
    GIGANTIC_SPRIGHT("gigantic_spright", 0x4A9AD4),   // 1070034
    KURIKARA_DIVINCARNATE("kurikara_divincarnate", 0xA64A3F),   // 1070035
    TEARLAMENTS_KALEIDO_HEART("tearlaments_kaleido_heart", 0x43589A),   // 1070036
    EXOSISTERS_MAGNIFICA("exosisters_magnifica", 0x66ABBB),   // 1070037
    P_U_N_K_JAM_DRAGON_DRIVE("p_u_n_k_jam_dragon_drive", 0x3BE3D8),   // 1070038
    VIDEO_GAME_AWARDS_2022_COMMEMORATION("video_game_awards_2022_commemoration", 0xAC53CD),   // 1070039
    FIVE_HEADED_DRAGON("five_headed_dragon", 0xA02E66),   // 1070040
    NUMBER_41_BAGOOSKA_THE_TERRIBLY_TIRED_TAPIR("number_41_bagooska_the_terribly_tired_tapir", 0x7E96B5),   // 1070041
    DC_2023_MAR_CELEBRATION("dc_2023_mar_celebration", 0x241350),   // 1070042
    INSTANT_CONTACT("instant_contact", 0xAEC25F),   // 1070043
    SPIRIT_CHARMERS("spirit_charmers", 0xC6A183),   // 1070044
    PENDULUM_GREEN("pendulum_green", 0x5E9F8C),   // 1070045
    WCS_2023_QUALIFIERS_CELEBRATION("wcs_2023_qualifiers_celebration", 0x3A6B90),   // 1070046
    MAYHEM_FUR_HIRE("mayhem_fur_hire", 0x7298A5),   // 1070047
    GHOTI_OF_THE_DEEP_BEYOND("ghoti_of_the_deep_beyond", 0x56739D),   // 1070048
    WITCHCRAFTER_VICE_MADAME("witchcrafter_vice_madame", 0x786B8F),   // 1070049
    THE_BYSTIAL_LUBELLION("the_bystial_lubellion", 0xD89749),   // 1070050
    TRAPTANTALIZING_TUNE("traptantalizing_tune", 0xD2AC76),   // 1070051
    REIGN_BEAUX_OVERKING_OF_DARK_WORLD("reign_beaux_overking_of_dark_world", 0xAC9D70),   // 1070052
    ROAD_TO_WORLDS_PROFICIENCY_TEST_2023("road_to_worlds_proficiency_test_2023", 0x160F76),   // 1070053
    CHAOS_ANGEL("chaos_angel", 0xA09168),   // 1070054
    BLACK_LUSTER_SOLDIER_LEGENDARY_SWORDSMAN("black_luster_soldier_legendary_swordsman", 0xAC566A),   // 1070055
    OHIME_THE_MANIFESTED_MIKANKO("ohime_the_manifested_mikanko", 0xDEC24A),   // 1070056
    KASHTIRA_ARISE_HEART("kashtira_arise_heart", 0xBC63B7),   // 1070057
    LIVE_TWIN_LIL_LA_TREAT("live_twin_lil_la_treat", 0x945CD3),   // 1070058
    WCS2023_LEGENDARY_MAGICIAN_OF_DARK("wcs2023_legendary_magician_of_dark", 0xA53C3C),   // 1070059
    WCS2023_LEGENDARY_DRAGON_OF_WHITE("wcs2023_legendary_dragon_of_white", 0xDAC55F),   // 1070060
    LIGHT_AND_DARKNESS_DRAGON("light_and_darkness_dragon", 0x5F5482),   // 1070061
    PROMETHEAN_PRINCESS_BESTOWER_OF_FLAMES("promethean_princess_bestower_of_flames", 0x983034),   // 1070062
    FIREWALL_DRAGON_SINGULARITY("firewall_dragon_singularity", 0x6F8FB4),   // 1070063
    STAKE_YOUR_SOUL("stake_your_soul", 0xB1494F),   // 1070064
    LIVE_TWIN_KI_SIKIL_FROST("live_twin_ki_sikil_frost", 0xB15B72),   // 1070065
    ALBION_THE_SANCTIFIRE_DRAGON("albion_the_sanctifire_dragon", 0xD1C17C),   // 1070066
    GOLD_PRIDE("gold_pride", 0xB3860B),   // 1070067
    SLIFER_THE_SKY_DRAGON("slifer_the_sky_dragon", 0xC1A148),   // 1070068
    WANTED_SEEKER_OF_SINFUL_SPOILS("wanted_seeker_of_sinful_spoils", 0xBF9368),   // 1070069
    BLUE_EYES_WHITE_DRAGON("blue_eyes_white_dragon", 0x262626),   // 1070070
    MAGICIANS_OF_BONDS_AND_UNITY("magicians_of_bonds_and_unity", 0x294B29),   // 1070071
    DRAGON_OF_PRIDE_AND_SOUL("dragon_of_pride_and_soul", 0x3B5588),   // 1070072
    SHADDOLL_FUSION("shaddoll_fusion", 0x386396),   // 1070073
    TEARLAMENTS_PERLEGIA("tearlaments_perlegia", 0x85C5F9),   // 1070074
    NIGHTMARE_MAGICIAN("nightmare_magician", 0xC1435F),   // 1070075
    THE_IRIS_SWORDSOUL("the_iris_swordsoul", 0xD0B980),   // 1070076
    CRIMSON_DRAGON("crimson_dragon", 0xB73838),   // 1070077
    EMPEROR_CHARLES_THE_GREAT("emperor_charles_the_great", 0xB54B24),   // 1070078
    SUPREME_KING_Z_ARC("supreme_king_z_arc", 0xBA6C64),   // 1070079
    IMSETY_GLORY_OF_HORUS("imsety_glory_of_horus", 0xD1B96A),   // 1070080
    VAALMONICA_SCELTA("vaalmonica_scelta", 0xA289B8),   // 1070081
    YUBEL_THE_LOVING_DEFENDER_FOREVER("yubel_the_loving_defender_forever", 0x5D3B4C),   // 1070082
    CENTUR_ION_PRIMERA("centur_ion_primera", 0xDFA269),   // 1070083
    DRAGON_MASTER_MAGIA("dragon_master_magia", 0x8C9DB6),   // 1070084
    TRAPTRIX_SERA("traptrix_sera", 0xBB9D49),   // 1070085
    DARK_MAGICIAN_GIRL("dark_magician_girl", 0x2B7AB3),   // 1070086
    DIABELLSTAR_THE_BLACK_WITCH("diabellstar_the_black_witch", 0x4B92A4),   // 1070087
    GALAXY_EYES_PHOTON_DRAGON("galaxy_eyes_photon_dragon", 0x6DADB2),   // 1070088
    FLOWER_CARDIAN_CHERRY_BLOSSOM_WITH_CURTAIN("flower_cardian_cherry_blossom_with_curtain", 0xA25D57),   // 1070089
    ALEISTER_THE_INVOKER_OF_MADNESS("aleister_the_invoker_of_madness", 0x9B594A),   // 1070090
    FLOWER_CARDIAN_ZEBRA_GRASS("flower_cardian_zebra_grass", 0xD67CA4),   // 1070091
    RAGNARAIKA_STAG_SOVEREIGN("ragnaraika_stag_sovereign", 0x4B4E69),   // 1070092
    RITUAL_BEAST_ULTI_REIRAUTARI("ritual_beast_ulti_reirautari", 0xC19C6E),   // 1070093
    FLOWER_CARDIAN_MAPLE_WITH_DEER("flower_cardian_maple_with_deer", 0xB56C59),   // 1070094
    STARDUST_DRAGON("stardust_dragon", 0x594F90),   // 1070095
    JUNK_WARRIOR("junk_warrior", 0xCB92CE),   // 1070096
    TRIPLE_TACTICS_TALENT("triple_tactics_talent", 0xBA924A),   // 1070097
    RED_EYES_DARK_DRAGOON("red_eyes_dark_dragoon", 0xC39C65),   // 1070098
    LIGHT_AND_DARKNESS_DRAGONLORD("light_and_darkness_dragonlord", 0xB3805B),   // 1070099
    TERMINAL_WORLD("terminal_world", 0x3B64D1),   // 1070100
    SKY_STRIKER_ACE_RAYE("sky_striker_ace_raye", 0x464646),   // 1070101
    ALUBER_THE_DOGMATIC("aluber_the_dogmatic", 0x9E4650),   // 1070102
    FIENDSMITH("fiendsmith", 0xA21A3D),   // 1070103
    KOCHOBO_S_HINAMATSURI("kochobo_s_hinamatsuri", 0xDAA157),   // 1070104
    BLUE_EYES_ULTIMATE_SPIRIT_DRAGON("blue_eyes_ultimate_spirit_dragon", 0xAFA179),   // 1070105
    NEVERENDING_NIGHTMARE_ABSORBER("neverending_nightmare_absorber", 0x6599AA),   // 1070106
    RED_EYES_BLACK_FULLMETAL_DRAGON("red_eyes_black_fullmetal_dragon", 0xC68044),   // 1070107
    PERFORMAGE_TRAPEZE_HIGH_MAGICIAN("performage_trapeze_high_magician", 0xBABE7D),   // 1070108
    FULL_ARMORED_DARK_KNIGHT_LANCER("full_armored_dark_knight_lancer", 0x4C7CC6),   // 1070109
    TEARLAMENTS_KITKALLOS("tearlaments_kitkallos", 0x77B3DE),   // 1070110
    TRAPTRIX_RAFFLESIA("traptrix_rafflesia", 0xB96C66),   // 1070111
    RGB_RAINBOWLUTION("rgb_rainbowlution", 0x59B6CC),   // 1070112
    DARK_SUPREMACY("dark_supremacy", 0xBD5C19),   // 1070113
    DOUBLE_WILD("double_wild", 0xE3985C),   // 1070114
    THE_FALLEN_THE_VIRTUOUS("the_fallen_the_virtuous", 0xC2C0BA),   // 1070115
    MATERIACTOR_EXAGARD("materiactor_exagard", 0x59B8DA),   // 1070116
    CRYSTRON_QUARIONGANDRAX("crystron_quariongandrax", 0xC8B15A),   // 1070117
    ARCANA_FORCE_XXI_THE_WORLD("arcana_force_xxi_the_world", 0x5D7F99),   // 1070118
    GLADIATOR_BEAST_GYZARUS("gladiator_beast_gyzarus", 0x446A72),   // 1070119
    ARC_REBELLION_XYZ_DRAGON("arc_rebellion_xyz_dragon", 0x685B83),   // 1070120
    BORRELOAD_FURIOUS_DRAGON("borreload_furious_dragon", 0x8C7CBE),   // 1070121
    MALISS_IN_THE_MIRROR("maliss_in_the_mirror", 0x77373C),   // 1070122
    CLEAR_WING_SYNCHRO_DRAGON("clear_wing_synchro_dragon", 0xD68569),   // 1070123
    RYZEAL_DETONATOR("ryzeal_detonator", 0xBC9044),   // 1070124
    ACCESSCODE_TALKER("accesscode_talker", 0xAC9857),   // 1070125
    REGENESIS_LORD("regenesis_lord", 0xB29D74),   // 1070126
    AME_NO_MURAKUMO_NO_MITSURUGI("ame_no_murakumo_no_mitsurugi", 0xC672DC),   // 1070127
    HERE_THERE_BE_DRAGONS("here_there_be_dragons", 0x425A99),   // 1070128
    CHEF_S_SPECIAL_RECIPE("chef_s_special_recipe", 0xC99573),   // 1070129
    EXODIA_THE_FORBIDDEN_ONE_WCS2025("exodia_the_forbidden_one_wcs2025", 0x9A6F31),   // 1070130
    HOUSE_DRAGONMAID("house_dragonmaid", 0x6C192B),   // 1070131
    DIABELLSTAR_THE_BLACK_WITCH_ALT("diabellstar_the_black_witch_alt", 0x4B92A4),   // 1070132
    LADY_LABRYNTH_OF_THE_SILVER_CASTLE("lady_labrynth_of_the_silver_castle", 0xA4A8D0),   // 1070133
    LADY_LABRYNTH_OF_THE_SILVER_CASTLE_ALT("lady_labrynth_of_the_silver_castle_alt", 0xA4A8D0),   // 1070134
    POT_OF_EXTRAVAGANCE("pot_of_extravagance", 0xD55969),   // 1070135
    HU_LI_THE_JEWEL_MIKANKO("hu_li_the_jewel_mikanko", 0xACD175),   // 1070137
    SKY_STRIKER_ACE_ZERO("sky_striker_ace_zero", 0x6FAFC6),   // 1070138
    DRACOTAIL_ARTHALION("dracotail_arthalion", 0x4A7D8F),   // 1070139
    NUMBER_F0_UTOPIC_FUTURE_ZEXAL("number_f0_utopic_future_zexal", 0xC7B160),   // 1070140
    ANUBIS_THE_LAST_JUDGE("anubis_the_last_judge", 0xA28954),   // 1070141
    ELDLIXIR_OF_THE_GLORIOUS_GOLDEN_LAND("eldlixir_of_the_glorious_golden_land", 0xC83823),   // 1070142
    LUNALIGHT_LIGER_DANCER("lunalight_liger_dancer", 0x3D4498),   // 1070143
    OTOSHIDAMASHI("otoshidamashi", 0x75C8E7),   // 1070144
    THE_STAR_HAM("the_star_ham", 0xDC8C54),   // 1070145
    D_D_D_D_DIMENSIONAL_KING_ARC_CRISIS("d_d_d_d_dimensional_king_arc_crisis", 0x714A9B),   // 1070146
    INFINITE_IMPERMANENCE("infinite_impermanence", 0x2C6F9A),   // 1070147
    PSYCHIC_END_PUNISHER("psychic_end_punisher", 0x2A9646),   // 1070148
    GRADIUS("gradius", 0xA4543E),   // 1070149
    W_P_FANCY_BALL("w_p_fancy_ball", 0xC39A53),   // 1070150
    K9_LUPIS("k9_lupis", 0xBB3238),   // 1070151
    SECRETS_OF_DARK_MAGIC("secrets_of_dark_magic", 0xA1344D),   // 1070152
    SPRIGHT_ELF("spright_elf", 0xCD5F64),   // 1070153
    MYSTICAL_SPACE_TYPHOON("mystical_space_typhoon", 0x5082A4),   // 1070154
    FUSION_DESTINY("fusion_destiny", 0x6E80CF),   // 1070155
    KEWL_TUNE_RS("kewl_tune_rs", 0x99523F),   // 1070156
    LIVE_TWIN_LIL_LA_SWEET("live_twin_lil_la_sweet", 0xD16FAD),   // 1070157
    JUNK_WARRIOR_EXTREME("junk_warrior_extreme", 0x1975D0),   // 1070158
    EMPEROR_TANUKI_S_CRITTER_COUNT("emperor_tanuki_s_critter_count", 0xB3616F),   // 1070159
    ASSAULT_MODE_ACTIVATE("assault_mode_activate", 0xD58F89),   // 1070160
    MASKED_HERO_ATOMIC("masked_hero_atomic", 0x7899C5),   // 1070161
    MASTER_PEACE_THE_TRUE_DRACOVERLORD("master_peace_the_true_dracoverlord", 0x8976BF),   // 1070162
    R_B_THE_BRUTE_BLUES("r_b_the_brute_blues", 0xC1912E),   // 1070163
    ULTIMATE_SLAYER("ultimate_slayer", 0x4F4C7B),   // 1070164
    ELFNOTE_REGINA("elfnote_regina", 0xA2AA5C),   // 1070165
    DRAGUNITY_KNIGHT_AREUS("dragunity_knight_areus", 0xD2A364),   // 1070166
    EXOSISTER_KARMAEL("exosister_karmael", 0xAA2C79),   // 1070167
    TELLER_OF_FAIRY_TAILS("teller_of_fairy_tails", 0x603E39),   // 1070168
    FOLGO_JUSTICE_FUR_HIRE("folgo_justice_fur_hire", 0xA3A8D7),   // 1070169
    RYZEAL_PLUGIN("ryzeal_plugin", 0xA97243),   // 1070170
    HECAHANDS_JAUZAH("hecahands_jauzah", 0x9D2E33),   // 1070171
    ARCHFIEND_EMPEROR("archfiend_emperor", 0x8F282E),   // 1070172
    ARCHFIEND_MATRIARCH("archfiend_matriarch", 0x60397D),   // 1070173
    STARVING_VENOM_WING_DRAGON("starving_venom_wing_dragon", 0x33598B),   // 1070174
    PUMPKING_THE_KING_OF_GRAVE_GHOSTS("pumpking_the_king_of_grave_ghosts", 0xBF6D2C),   // 1070175
    STELLARNOVA_ALPHA("stellarnova_alpha", 0xE26F8A),   // 1070176
    SUPERDREADNOUGHT_RAIL_CANNON_JUGGERNAUT_LIEBE("superdreadnought_rail_cannon_juggernaut_liebe", 0x8D7256),   // 1070177
    MOKOMOKO("mokomoko", 0x816841),   // 1070178
    FAVORITE_HERO("favorite_hero", 0xC5CF9F),   // 1070179
    EL_SHADDOLL_CONSTRUCT("el_shaddoll_construct", 0x9775B3),   // 1070180
    POLYMERIZATION("polymerization", 0x2E77B4),   // 1070184
    FIFTH_HOPE("fifth_hope", 0x768EBF),   // 1070189
    CRUSADIA_MAXIMUS("crusadia_maximus", 0xB4A17C),   // 1071001
    LONGIRSU_THE_ORCUST_ORCHESTRATOR("longirsu_the_orcust_orchestrator", 0xAD9268),   // 1071002
    DREAM_MIRROR_PHANTASMS("dream_mirror_phantasms", 0x5A387C),   // 1071003
    SIX_SAMURAI_UNITED("six_samurai_united", 0x7098A4),   // 1071004
    DANGER_BIGFOOT("danger_bigfoot", 0x84A1B2),   // 1071005
    NEPHTHYS_THE_SACRED_FLAME("nephthys_the_sacred_flame", 0xBA6662),   // 1071006
    U_A_PLAYMAKER("u_a_playmaker", 0x305B75),   // 1071007
    BLACKBEARD_THE_PLUNDER_PATROLL_CAPTAIN("blackbeard_the_plunder_patroll_captain", 0x7CABBF),   // 1071008
    BUJINTEI_SUSANOWO("bujintei_susanowo", 0xC19570),   // 1071009
    ALLY_OF_JUSTICE_CATASTOR("ally_of_justice_catastor", 0x3D4E85),   // 1071010
    MERMAIL_ABYSSMEGALO("mermail_abyssmegalo", 0x4B76AA),   // 1071011
    GIANT_BEETROOPER_INVINCIBLE_ATLAS("giant_beetrooper_invincible_atlas", 0xC2846C),   // 1071012
    REVENDREAD_SLAYER("revendread_slayer", 0x778FA6),   // 1071013
    GHOSTRICK_ALUCARD("ghostrick_alucard", 0x662250),   // 1071014
    YOKO_THE_GRACEFUL_MAYAKASHI("yoko_the_graceful_mayakashi", 0x5CC0D0),   // 1071015
    LEGENDARY_SIX_SAMURAI_SHI_EN("legendary_six_samurai_shi_en", 0xCD81C4),   // 1071016
    GENEX_CONTROLLER("genex_controller", 0x413646),   // 1071017
    MYUTANT_ULTIMUS("myutant_ultimus", 0xB34186),   // 1071018
    STARRY_NIGHT_STARRY_DRAGON("starry_night_starry_dragon", 0x6999BC),   // 1071019
    MEKK_KNIGHT_CRUSADIA_AVRAMAX("mekk_knight_crusadia_avramax", 0x5EBCD4),   // 1071020
    DINGIRSU_THE_ORCUST_OF_THE_EVENING_STAR("dingirsu_the_orcust_of_the_evening_star", 0xB6AD7F),   // 1071021
    S_FORCE_JUSTIFY("s_force_justify", 0xD0702B),   // 1071022
    TEARDROP_THE_RIKKA_QUEEN("teardrop_the_rikka_queen", 0xA4BFE2),   // 1071023
    SUBTERROR_BEHEMOTH_SPELEOGEIST("subterror_behemoth_speleogeist", 0x34C7D8),   // 1071024
    DRACO_MASTERS_OF_THE_TENYI("draco_masters_of_the_tenyi", 0xC8A562),   // 1071025
    COMMANDER_GOTTOMS_SWORDMASTER("commander_gottoms_swordmaster", 0x495B8A),   // 1071026
    ELDLIXIR_OF_BLACK_AWAKENING("eldlixir_of_black_awakening", 0x414453),   // 1071027
    NATURIA_LEODRAKE("naturia_leodrake", 0xD47728),   // 1071028
    FABLED_LEVIATHAN("fabled_leviathan", 0x88332F),   // 1071029
    ALLY_OF_JUSTICE_FIELD_MARSHAL("ally_of_justice_field_marshal", 0xCBAF74),   // 1071030
    MIST_VALLEY_APEX_AVIAN("mist_valley_apex_avian", 0xBD9926),   // 1071031
    SKULL_SERVANT("skull_servant", 0x341F58),   // 1071032
    SKY_STRIKER_ACE_RAYE_ALT("sky_striker_ace_raye_alt", 0x464646),   // 1071033
    FLAMVELL_URUQUIZAS("flamvell_uruquizas", 0xCD8514),   // 1071034
    FIRE_KING_HIGH_AVATAR_GARUNIX("fire_king_high_avatar_garunix", 0x87352C),   // 1071035
    POSEIDRA_THE_ATLANTEAN_DRAGON("poseidra_the_atlantean_dragon", 0x6F95B0),   // 1071036
    THAT_GRASS_LOOKS_GREENER("that_grass_looks_greener", 0x387C2C),   // 1071037
    I_P_MASQUERENA("i_p_masquerena", 0x6A42AE),   // 1071038
    WORM_ZERO("worm_zero", 0x6E7A86),   // 1071039
    OBEDIENCE_SCHOOLED("obedience_schooled", 0xCE65A4),   // 1071040
    SKY_STRIKER_CONVERSION_FLAMING_WINGS_OF_DESTRUCTION("sky_striker_conversion_flaming_wings_of_destruction", 0xAE5C43),   // 1072001
    CHAOS_XYZ_EVOLUTION_GALACTIC_GATHERING_OF_DRAGONS("chaos_xyz_evolution_galactic_gathering_of_dragons", 0xBE756F),   // 1072002
    SKY_STRIKER_ARMOR_BLACK_FLASH_RAIMENT("sky_striker_armor_black_flash_raiment", 0x9E835F),   // 1072003
    HALLO_WEEN("hallo_ween", 0x3C5E76),   // 1072004
    EVIL_TWIN("evil_twin", 0x5165B0),   // 1072005
    THE_ORCUST_MEKK_KNIGHT_AUTOMATON("the_orcust_mekk_knight_automaton", 0xC1A9D4),   // 1072006
    MALISS_Q("maliss_q", 0x6480A5),   // 1072007
    YUMMY("yummy", 0xE0AE69),   // 1072008
    ALBAZ_THE_SHROUDED_ECCLESIA_THE_EXILED("albaz_the_shrouded_ecclesia_the_exiled", 0x6A3F30),   // 1072009
    ENNEACRAFT("enneacraft", 0xD0A35B),   // 1072010
    WCS_2023_PARTY_FAVOR("wcs_2023_party_favor", 0x713BB8),   // 1073001
    WCS_2023_CELEBRATION("wcs_2023_celebration", 0x861518),   // 1073002
    DC_2023_OCT_CELEBRATION("dc_2023_oct_celebration", 0x241351),   // 1073003
    DC_2023_DEC_CELEBRATION("dc_2023_dec_celebration", 0x241351),   // 1073004
    DC_2024_MAR_CELEBRATION("dc_2024_mar_celebration", 0x241350),   // 1073005
    WCS_2024_QUALIFIERS_CELEBRATION("wcs_2024_qualifiers_celebration", 0x3A6B90),   // 1073006
    XYZ_CUP_CELEBRATION("xyz_cup_celebration", 0x200F51),   // 1073007
    WCS_2024_CELEBRATION("wcs_2024_celebration", 0x871518),   // 1073008
    WCS_2024_PARTY_FAVOR("wcs_2024_party_favor", 0x713BB8),   // 1073009
    DC_2024_SEP_CELEBRATION("dc_2024_sep_celebration", 0x241351),   // 1073010
    DC_2024_DEC_CELEBRATION("dc_2024_dec_celebration", 0x241351),   // 1073011
    DC_2025_MAR_CELEBRATION("dc_2025_mar_celebration", 0x241350),   // 1073012
    WCS_2025_QUALIFIERS_CELEBRATION("wcs_2025_qualifiers_celebration", 0x3A6B90),   // 1073013
    SYNCHRO_CUP_CELEBRATION("synchro_cup_celebration", 0x428769),   // 1073014
    WCS_2025_CELEBRATION("wcs_2025_celebration", 0x861518),   // 1073015
    WCS_2025_PARTY_FAVOR("wcs_2025_party_favor", 0x713BB8),   // 1073016
    DC_2025_SEP_CELEBRATION("dc_2025_sep_celebration", 0x241351),   // 1073017
    DC_2025_DEC_CELEBRATION("dc_2025_dec_celebration", 0x241351),   // 1073018
    DC_2026_MAR_CELEBRATION("dc_2026_mar_celebration", 0x241350),   // 1073019
    WCS_2026_QUALIFIERS_CELEBRATION("wcs_2026_qualifiers_celebration", 0x3A6B90),   // 1073020
    FUSION_CUP_CELEBRATION("fusion_cup_celebration", 0xA11C24),   // 1073023
    YU_GI_OH_CARD_GAME_THE_CHRONICLES("yu_gi_oh_card_game_the_chronicles", 0xB29776),   // 1075001
    THE_CHRONICLES_SKY_STRIKER_ACE("the_chronicles_sky_striker_ace", 0xB24755),   // 1075002
    WHITE_BLUE("white_blue", 0x253699),   // 1075003
    EFOOTBALL("efootball", 0xF4F40A),   // 1075004
    NEYMAR("neymar", 0x5F8BCA),   // 1075005
    THE_CHRONICLES_THE_FALLEN_THE_VIRTUOUS("the_chronicles_the_fallen_the_virtuous", 0xD4BB76),   // 1075006
    THE_CHRONICLES_THE_FALLEN_THE_VIRTUOUS2("the_chronicles_the_fallen_the_virtuous2", 0xBA8158),   // 1075007
    THE_CHRONICLES_SPIRIT_CHARMERS("the_chronicles_spirit_charmers", 0xC29F79),   // 1075008
    THE_CHRONICLES_MAGISTUS("the_chronicles_magistus", 0x6395BC);   // 1075009

    public static final CardSleevesType[] VALUES = CardSleevesType.values();
    
    public static CardSleevesType getFromIndex(byte index)
    {
        return CardSleevesType.VALUES[index];
    }
    
    static
    {
        byte index = 0;
        for(CardSleevesType duelPhase : CardSleevesType.VALUES)
        {
            duelPhase.index = index++;
        }
    }
    
    public final String name;
    public final boolean isPatreonReward;
    public final String patronName;
    private byte index;

    /**
     * A representative colour, so a shop can sort by it.
     * <p>
     * NOT the average of the art. Averaging these illustrations flat turns a red
     * dragon on black and a blue dragon on black into the same grey-brown, and
     * sorting by that sorts by nothing. This is the DOMINANT colour: the peak of
     * a saturation-weighted hue histogram, which is a colour the sleeve actually
     * has rather than the blend of two it has. Sampled offline by
     * {@code tools/sample_sleeve_colors.py}, which compares the methods on a
     * contact sheet of the whole catalogue.
     * <p>
     * 0xRRGGBB, no alpha.
     */
    public final int colour;

    /**
     * That colour as hue and brightness, worked out once, here.
     * <p>
     * Derived at construction rather than per comparison: sorting the catalogue
     * calls the comparator well over a thousand times and an HSB conversion in
     * each is arithmetic nobody needs repeated.
     */
    private final float hue;
    private final float brightness;
    private final boolean chromatic;

    /**
     * Below this saturation a hue is noise rather than a colour.
     * <p>
     * A near-grey sleeve still has a hue, but it is whatever rounding produced,
     * and interleaving those with real colours makes both look unsorted. They
     * sort together instead, by brightness.
     */
    public static final float COLOUR_ACHROMATIC = 0.15F;

    CardSleevesType(String name, int colour, boolean isPatreonReward, String patron)
    {
        this.name = name;
        this.colour = colour;
        this.isPatreonReward = isPatreonReward;
        patronName = patron;

        float r = ((colour >> 16) & 0xFF) / 255F;
        float g = ((colour >> 8) & 0xFF) / 255F;
        float b = (colour & 0xFF) / 255F;
        float max = Math.max(r, Math.max(g, b));
        float min = Math.min(r, Math.min(g, b));
        float span = max - min;
        brightness = max;
        chromatic = max > 0F && span / max >= COLOUR_ACHROMATIC;
        float h;
        if(span <= 0F)
        {
            h = 0F;
        }
        else if(max == r)
        {
            h = ((g - b) / span) / 6F;
        }
        else if(max == g)
        {
            h = (2F + (b - r) / span) / 6F;
        }
        else
        {
            h = (4F + (r - g) / span) / 6F;
        }
        hue = (h % 1F + 1F) % 1F;
    }

    CardSleevesType(String name, int colour)
    {
        this(name, colour, false, null);
    }

    CardSleevesType(String name, int colour, String patron)
    {
        this(name, colour, true, patron);
    }

    /**
     * Orders sleeves the way the eye groups them: the greys first, by
     * brightness, then everything else round the colour wheel.
     * <p>
     * Ascending. Reversing it is the descending arrow's job, not this method's.
     */
    public static int compareByColour(CardSleevesType a, CardSleevesType b)
    {
        if(a.chromatic != b.chromatic)
        {
            return a.chromatic ? 1 : -1;
        }
        if(!a.chromatic)
        {
            return Float.compare(a.brightness, b.brightness);
        }
        int byHue = Float.compare(a.hue, b.hue);
        return byHue != 0 ? byHue : Float.compare(a.brightness, b.brightness);
    }

    public boolean isCardBack()
    {
        return this == CARD_BACK;
    }

    
    /**
     * The largest tier a sleeve actually ships at.
     * <p>
     * The catalogue is Master Duel's protectors, whose source art is 512 pixels
     * wide. Once the card window's own 0.602 of the canvas is taken out, a 1024
     * canvas would be storing a 1.2x upscale of that -- a hundred and sixty
     * megabytes across the catalogue for detail that is not in the file.
     * <p>
     * Clamped in {@link #getMainRL} rather than left to callers: a caller that
     * asks for 1024 gets the 512 texture, where before it got a resource
     * location that resolves to nothing and a magenta card back. See
     * tools/import_sleeves.py, which writes exactly these tiers.
     */
    public static final int MAX_SIZE = 512;

    public Identifier getMainRL(int size)
    {
        return Identifier.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/item/" + Math.min(size, MAX_SIZE) + "/" + getResourceName() + ".png");
    }

    public Identifier getItemModelRL(int size)
    {
        if(isCardBack())
        {
            return null;
        }
        else
        {
            return Identifier.fromNamespaceAndPath(DuelDimension.MOD_ID, getResourceName() + "_" + Math.min(size, MAX_SIZE));
        }
    }
    
    public String getResourceName()
    {
        if(isCardBack())
        {
            return name;
        }
        else
        {
            return "sleeves_" + name;
        }
    }
    
    public Item getItem()
    {
        // Registries are looked up directly now: BuiltInRegistries is the
        // registry itself, where ForgeRegistries was a wrapper around it.
        return net.minecraft.core.registries.BuiltInRegistries.ITEM.getValue(
            Identifier.fromNamespaceAndPath(DuelDimension.MOD_ID, getResourceName()));
    }
    
    public byte getIndex()
    {
        return index;
    }
}
