package de.cas_ual_ty.dueldimension.ocg.deck;

import java.util.List;

/**
 * Every structure deck the card database describes, as a deck that can be
 * played. Generated by {@code tools/gen_structure_deck.py} from the set data --
 * the deck IS the set, so every card in one is obtainable in game.
 * <p>
 * <b>Do not edit by hand.</b> The generator writes both the {@code .ydk} files
 * and this class, precisely so the registry cannot name a deck the resources do
 * not contain.
 * <p>
 * Sets listing fewer than forty main-deck cards are absent: those are special
 * editions and box sets that list no cards at all, plus a couple of early decks
 * that were genuinely short. A deck that cannot legally be played is worse than
 * one that is not offered.
 */
public final class StructureDecks
{
    /**
     * @param id          resource/deck slug
     * @param displayName shown to the player
     * @param setCode     the TCG set this deck reproduces
     * @param mainCount   main deck size, for a picker that wants to show it
     * @param extraCount  extra deck size
     */
    public record Entry(String id, String displayName, String setCode,
        int mainCount, int extraCount)
    {
        public String resourcePath()
        {
            return "data/dueldimension/decks/structure/" + id + ".ydk";
        }

        public YdkDeck load()
        {
            return YdkDeck.loadResource(resourcePath());
        }
    }

    private StructureDecks()
    {
    }

    public static final List<Entry> ALL = List.of(
        new Entry("albaz_strike", "Structure Deck: Albaz Strike", "SDAZ", 40, 6),
        new Entry("beware_of_traptrix", "Structure Deck: Beware of Traptrix", "SDBT", 40, 6),
        new Entry("blaze_of_destruction", "Structure Deck: Blaze of Destruction", "SD3", 40, 0),
        new Entry("cyber_dragon_revolution", "Cyber Dragon Revolution Structure Deck", "SDCR", 40, 2),
        new Entry("cyber_strike", "Structure Deck: Cyber Strike", "SDCS", 43, 5),
        new Entry("cyberse_link", "Structure Deck: Cyberse Link", "SDCL", 40, 3),
        new Entry("dark_world", "Structure Deck: Dark World", "SR13", 44, 1),
        new Entry("dinosmasher_s_fury", "Dinosmasher's Fury Structure Deck", "SR04", 41, 0),
        new Entry("dragon_s_roar", "Structure Deck: Dragon's Roar", "SD1", 40, 0),
        new Entry("dragons_collide", "Dragons Collide Structure Deck", "SDDC", 40, 0),
        new Entry("dragunity_legion", "Dragunity Legion Structure Deck", "SDDL", 40, 0),
        new Entry("emperor_of_darkness", "Emperor of Darkness Structure Deck", "SR01", 41, 0),
        new Entry("fire_kings", "Structure Deck: Fire Kings", "SR14", 43, 4),
        new Entry("freezing_chains", "Structure Deck: Freezing Chains", "SDFC", 41, 5),
        new Entry("fury_from_the_deep", "Structure Deck: Fury from the Deep", "SD4", 40, 0),
        new Entry("gates_of_the_underworld", "Gates of the Underworld Structure Deck", "SDGU", 40, 0),
        new Entry("geargia_rampage", "Geargia Rampage Structure Deck", "SDGR", 40, 2),
        new Entry("hero_strike", "HERO Strike Structure Deck", "SDHS", 40, 5),
        new Entry("invincible_fortress", "Structure Deck: Invincible Fortress", "SD7", 40, 0),
        new Entry("lair_of_darkness", "Structure Deck: Lair of Darkness", "SR06", 41, 0),
        new Entry("legend_of_the_crystal_beasts", "Structure Deck: Legend of the Crystal Beasts", "SDCB", 44, 2),
        new Entry("lord_of_the_storm", "Structure Deck: Lord of the Storm", "SD8", 40, 0),
        new Entry("lost_sanctuary", "Lost Sanctuary Structure Deck", "SDLS", 40, 0),
        new Entry("machina_mayhem", "Machina Mayhem Structure Deck", "SDMM", 40, 0),
        new Entry("machine_re_volt", "Structure Deck: Machine Re-Volt", "SD10", 40, 0),
        new Entry("machine_reactor", "Machine Reactor Structure Deck", "SR03", 41, 0),
        new Entry("marik_tcg", "Structure Deck: Marik (TCG)", "SDMA", 42, 0),
        new Entry("master_of_pendulum", "Master of Pendulum Structure Deck", "SDMP", 40, 3),
        new Entry("mechanized_madness", "Structure Deck: Mechanized Madness", "SR10", 42, 0),
        new Entry("onslaught_of_the_fire_kings", "Onslaught of the Fire Kings Structure Deck", "SDOK", 40, 0),
        new Entry("order_of_the_spellcasters", "Structure Deck: Order of the Spellcasters", "SR08", 41, 1),
        new Entry("pendulum_domination", "Pendulum Domination Structure Deck", "SDPD", 40, 3),
        new Entry("powercode_link", "Structure Deck: Powercode Link", "SDPL", 40, 3),
        new Entry("realm_of_light", "Realm of Light Structure Deck", "SDLI", 40, 1),
        new Entry("realm_of_the_sea_emperor", "Realm of the Sea Emperor Structure Deck", "SDRE", 40, 0),
        new Entry("rise_of_the_dragon_lords", "Rise of the Dragon Lords Structure Deck", "SDRL", 40, 0),
        new Entry("rise_of_the_true_dragons", "Rise of the True Dragons Structure Deck", "SR02", 41, 0),
        new Entry("rokket_revolt", "Structure Deck: Rokket Revolt", "SDRR", 40, 6),
        new Entry("sacred_beasts", "Structure Deck: Sacred Beasts", "SDSA", 44, 2),
        new Entry("saga_of_blue_eyes_white_dragon", "Saga of Blue-Eyes White Dragon Structure Deck", "SDBE", 40, 1),
        new Entry("samurai_warlords", "Samurai Warlords Structure Deck", "SDWA", 40, 1),
        new Entry("seto_kaiba", "Structure Deck: Seto Kaiba", "SDKS", 40, 5),
        new Entry("shaddoll_showdown", "Structure Deck: Shaddoll Showdown", "SDSH", 41, 8),
        new Entry("soulburner", "Structure Deck: Soulburner", "SDSB", 40, 6),
        new Entry("spellcaster_s_command", "Spellcaster's Command Structure Deck", "SDSC", 40, 0),
        new Entry("spellcaster_s_judgment", "Structure Deck: Spellcaster's Judgment", "SD6", 40, 0),
        new Entry("synchron_extreme", "Synchron Extreme Structure Deck", "SDSE", 40, 4),
        new Entry("the_crimson_king", "Structure Deck: The Crimson King", "SDCK", 40, 9),
        new Entry("the_dark_emperor", "The Dark Emperor Structure Deck", "SDDE", 40, 0),
        new Entry("warrior_s_triumph", "Structure Deck: Warrior's Triumph", "SD5", 40, 0),
        new Entry("warriors_strike", "Warriors' Strike Structure Deck", "SDWS", 40, 0),
        new Entry("wave_of_light", "Structure Deck: Wave of Light", "SR05", 41, 0),
        new Entry("yugi_muto", "Structure Deck: Yugi Muto", "SDMY", 40, 5),
        new Entry("zombie_horde", "Structure Deck: Zombie Horde", "SR07", 41, 1),
        new Entry("zombie_world", "Zombie World Structure Deck", "SDZW", 40, 0));

    /** The deck of that id, or null if there is not one. */
    public static Entry byId(String id)
    {
        for(Entry entry : ALL)
        {
            if(entry.id().equals(id))
            {
                return entry;
            }
        }
        return null;
    }
}
