package de.cas_ual_ty.dueldimension.clientutil.hub;

import de.cas_ual_ty.dueldimension.DuelDimension;
import net.minecraft.resources.ResourceLocation;

/** The hub's furniture, all of it PNG. Generated by {@code tools/gen_hub_ui.py}. */
public final class HubTextures
{
    private static ResourceLocation gui(String path)
    {
        return ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/gui/" + path);
    }

    /**
     * The re-themable furniture.
     * <p>
     * These name INDEXED MASTERS, not pictures -- see {@link MenuThemes}. They
     * are still handed around and drawn exactly as before; {@link NineSlice}
     * swaps in a texture painted in the active palette on the way past. The
     * paths are the only thing that moved.
     */
    /** Nine-slice container, raised. */
    public static final ResourceLocation PANEL = gui("indexed/panel.png");
    /** Nine-slice container, recessed: lists and fields sit in these. */
    public static final ResourceLocation PANEL_INSET = gui("indexed/panel_inset.png");
    /** Three rows: idle, hovered, disabled. */
    public static final ResourceLocation BUTTON = gui("indexed/button.png");
    /** Three rows: idle, hovered, selected. */
    public static final ResourceLocation TAB = gui("indexed/tab.png");
    /** A single card slot for the deck editor grids. */
    public static final ResourceLocation SLOT = gui("indexed/slot.png");
    /**
     * A tick, white so it can be tinted to whatever the label beside it would
     * have been. Drawn by {@link HubWidgets.IconButton}.
     */
    public static final ResourceLocation CHECK = gui("common/check.png");

    /**
     * Marks a revealed card the collection did not already hold.
     * <p>
     * Art, because the word never changes -- see CLAUDE.md. Drawn at its own
     * size, {@link #NEW_BADGE_W} by {@link #NEW_BADGE_H}: GUI textures sample
     * nearest, so a badge blitted 1:1 is pixel exact at every gui scale, where
     * one stretched to a fraction of a card's width would shimmer as the card
     * animates. Generated by tools/make_new_badge.py.
     */
    public static final ResourceLocation NEW_BADGE = gui("common/new_badge.png");

    /**
     * The mark on a card nominated as a Destiny Card.
     * <p>
     * A "D" on a disc, in the shape language of the banlist badges beside it,
     * and violet so it cannot be mistaken for either of them or for the star.
     */
    public static final ResourceLocation DESTINY_CARD = gui("common/destiny_card.png");

    /** The ordinary draw, offered beside it. */
    public static final ResourceLocation NORMAL_DRAW = gui("common/normal_draw.png");

    public static final int NEW_BADGE_W = 27;
    public static final int NEW_BADGE_H = 13;
    /**
     * Sort direction, replacing the words ASC and DESC. White for the same
     * reason the tick is: {@link HubWidgets.IconButton} tints them.
     */
    public static final ResourceLocation SORT_UP = gui("common/sort_up.png");
    public static final ResourceLocation SORT_DOWN = gui("common/sort_down.png");

    /** Fixed-ratio Master Duel deck tile, without its interaction outline. */
    public static final ResourceLocation DECK_TILE = gui("hub/deck_tile_surface.png");
    /** The active deck's rank plate, already clipped to the tile silhouette. */
    public static final ResourceLocation DECK_TILE_SELECTED = gui("hub/deck_tile_selected.png");
    /** Three full-size rows: idle, hovered and active deck outlines. */
    public static final ResourceLocation DECK_TILE_FRAME = gui("hub/deck_tile_frame.png");
    /** Temporary deck case used until deck-specific cases are part of profile data. */
    public static final ResourceLocation DECK_PLACEHOLDER = gui("hub/deck_placeholder.png");
    public static final ResourceLocation DECK_BOX_RED = gui("hub/deck_box_red.png");
    public static final ResourceLocation DECK_BOX_PURPLE = gui("hub/deck_box_purple.png");
    public static final ResourceLocation DECK_BOX_VORTEX_OF_MAGIC =
        gui("hub/deck_box_vortex_of_magic.png");
    public static final ResourceLocation DECK_BOX_BLUE_EYES_MAX =
        gui("hub/deck_box_blue_eyes_max.png");
    public static final ResourceLocation DECK_BOX_DARK_MAGICAL_BLAST =
        gui("hub/deck_box_dark_magical_blast.png");
    public static final ResourceLocation DECK_BOX_RAGE_OF_DEEP_BLUE =
        gui("hub/deck_box_rage_of_deep_blue.png");
    public static final ResourceLocation DECK_BOX_CYBER_KAISER =
        gui("hub/deck_box_cyber_kaiser.png");
    public static final ResourceLocation DECK_BOX_HEIR_TO_THE_SHIRANUI_STYLE =
        gui("hub/deck_box_heir_to_the_shiranui_style.png");
    public static final ResourceLocation DECK_BOX_EMERGENCE_OF_THE_MONARCHS =
        gui("hub/deck_box_emergence_of_the_monarchs.png");
    public static final ResourceLocation DECK_BOX_GEM_KNIGHTS_RESOLUTION =
        gui("hub/deck_box_gem_knights_resolution.png");
    public static final ResourceLocation DECK_BOX_BURNING_SPIRITS =
        gui("hub/deck_box_burning_spirits.png");
    public static final ResourceLocation DECK_BOX_XYZ_BLACK =
        gui("hub/deck_box_xyz_black.png");
    public static final ResourceLocation DECK_BOX_CARD_CASE_WIND =
        gui("hub/deck_box_card_case_wind.png");
    public static final ResourceLocation DECK_BOX_LINK_BLUE =
        gui("hub/deck_box_link_blue.png");
    public static final ResourceLocation DECK_BOX_RE_CONTRACT_UNIVERSE =
        gui("hub/deck_box_re_contract_universe.png");
    public static final ResourceLocation DECK_BOX_MAGICIAN_OF_PENDULUM =
        gui("hub/deck_box_magician_of_pendulum.png");
    public static final ResourceLocation DECK_BOX_RAGE_OF_CIPHER =
        gui("hub/deck_box_rage_of_cipher.png");
    public static final ResourceLocation DECK_BOX_CYBERNETIC_SUCCESSOR =
        gui("hub/deck_box_cybernetic_successor.png");
    public static final ResourceLocation DECK_BOX_GROWING_DIGITAL_BUG =
        gui("hub/deck_box_growing_digital_bug.png");
    public static final ResourceLocation DECK_BOX_ROAR_OF_THE_GLADIATOR_BEASTS =
        gui("hub/deck_box_roar_of_the_gladiator_beasts.png");
    public static final ResourceLocation DECK_BOX_BEING_WHO_SEES_THE_END_OF_THE_WORLD =
        gui("hub/deck_box_being_who_sees_the_end_of_the_world.png");
    public static final ResourceLocation DECK_BOX_DRAGONMAID_TO_ORDER =
        gui("hub/deck_box_dragonmaid_to_order.png");
    public static final ResourceLocation DECK_BOX_SPELLBOOK_OF_PROPHECY =
        gui("hub/deck_box_spellbook_of_prophecy.png");
    public static final ResourceLocation DECK_BOX_IMMORTAL_GLORY =
        gui("hub/deck_box_immortal_glory.png");
    public static final ResourceLocation DECK_BOX_SPIRAL_SPEAR_STRIKE =
        gui("hub/deck_box_spiral_spear_strike.png");
    public static final ResourceLocation DECK_BOX_BLACKWING_S_PRIDE =
        gui("hub/deck_box_blackwing_s_pride.png");
    public static final ResourceLocation DECK_BOX_HIDDEN_ARTS_OF_SHADOWS =
        gui("hub/deck_box_hidden_arts_of_shadows.png");
    public static final ResourceLocation DECK_BOX_SWORD_OF_SOULS =
        gui("hub/deck_box_sword_of_souls.png");
    public static final ResourceLocation DECK_BOX_ORIGIN_OF_THE_GALAXY =
        gui("hub/deck_box_origin_of_the_galaxy.png");
    public static final ResourceLocation DECK_BOX_HEROES_UNION =
        gui("hub/deck_box_heroes_union.png");
    public static final ResourceLocation DECK_BOX_BLAZE_OF_ALBAZ =
        gui("hub/deck_box_blaze_of_albaz.png");
    public static final ResourceLocation DECK_BOX_CRIMSON_POWERFORCE =
        gui("hub/deck_box_crimson_powerforce.png");
    public static final ResourceLocation DECK_BOX_REUNION_OF_RAIDERS =
        gui("hub/deck_box_reunion_of_raiders.png");
    public static final ResourceLocation DECK_BOX_GIGANTIC_SPARKLE =
        gui("hub/deck_box_gigantic_sparkle.png");
    public static final ResourceLocation DECK_BOX_ZERO_TO_FUTURE =
        gui("hub/deck_box_zero_to_future.png");
    public static final ResourceLocation DECK_BOX_DUELIST_CARD_CASE_BLUE =
        gui("hub/deck_box_duelist_card_case_blue.png");
    public static final ResourceLocation DECK_BOX_CARD_CASE_LIGHT =
        gui("hub/deck_box_card_case_light.png");
    public static final ResourceLocation DECK_BOX_CARD_CASE_DARK =
        gui("hub/deck_box_card_case_dark.png");
    public static final ResourceLocation DECK_BOX_CARD_CASE_EARTH =
        gui("hub/deck_box_card_case_earth.png");
    public static final ResourceLocation DECK_BOX_CARD_CASE_WATER =
        gui("hub/deck_box_card_case_water.png");
    public static final ResourceLocation DECK_BOX_CARD_CASE_FIRE =
        gui("hub/deck_box_card_case_fire.png");
    public static final ResourceLocation DECK_BOX_GOLD_PRIDE =
        gui("hub/deck_box_gold_pride.png");
    public static final ResourceLocation DECK_BOX_CASE_2024_CARD_CASE =
        gui("hub/deck_box_2024_card_case.png");
    public static final ResourceLocation DECK_BOX_PRESIDENT_S_BRIEFCASE =
        gui("hub/deck_box_president_s_briefcase.png");
    public static final ResourceLocation DECK_BOX_MAGICIANS_OF_BONDS_AND_UNITY =
        gui("hub/deck_box_magicians_of_bonds_and_unity.png");
    public static final ResourceLocation DECK_BOX_KING_S_SARCOPHAGUS =
        gui("hub/deck_box_king_s_sarcophagus.png");
    public static final ResourceLocation DECK_BOX_SNAKE_PATTERN =
        gui("hub/deck_box_snake_pattern.png");
    public static final ResourceLocation DECK_BOX_HALLO_WEEN =
        gui("hub/deck_box_hallo_ween.png");
    public static final ResourceLocation DECK_BOX_LIVE_TWIN =
        gui("hub/deck_box_live_twin.png");
    public static final ResourceLocation DECK_BOX_DRAGON_OF_PRIDE_AND_SOUL =
        gui("hub/deck_box_dragon_of_pride_and_soul.png");
    public static final ResourceLocation DECK_BOX_SKY_STRIKER_ACE_RAYE =
        gui("hub/deck_box_sky_striker_ace_raye.png");
    public static final ResourceLocation DECK_BOX_SKY_STRIKER_ACE_ROZE =
        gui("hub/deck_box_sky_striker_ace_roze.png");
    public static final ResourceLocation DECK_BOX_ABYSSAL_LAND =
        gui("hub/deck_box_abyssal_land.png");
    public static final ResourceLocation DECK_BOX_ORCUST =
        gui("hub/deck_box_orcust.png");
    public static final ResourceLocation DECK_BOX_YUM_YUM_YUMMYS =
        gui("hub/deck_box_yum_yum_yummys.png");
    public static final ResourceLocation DECK_BOX_DIABELLSTAR_THE_BLACK_WITCH =
        gui("hub/deck_box_diabellstar_the_black_witch.png");
    public static final ResourceLocation DECK_BOX_LABRYNTH =
        gui("hub/deck_box_labrynth.png");
    public static final ResourceLocation DECK_BOX_A_CASE_FOR_K9 =
        gui("hub/deck_box_a_case_for_k9.png");
    public static final ResourceLocation DECK_BOX_CLOCK_TOWER_PRISON =
        gui("hub/deck_box_clock_tower_prison.png");
    public static final ResourceLocation DECK_BOX_KEWL_TUNE =
        gui("hub/deck_box_kewl_tune.png");
    public static final ResourceLocation DECK_BOX_ELFNOTE =
        gui("hub/deck_box_elfnote.png");
    public static final ResourceLocation DECK_BOX_DRAGON_RAVINE =
        gui("hub/deck_box_dragon_ravine.png");
    public static final ResourceLocation DECK_BOX_EXOSISTER =
        gui("hub/deck_box_exosister.png");
    public static final ResourceLocation DECK_BOX_WHITE_BLUE =
        gui("hub/deck_box_white_blue.png");
    public static final ResourceLocation DECK_BOX_MILLENNIUM_PUZZLE =
        gui("hub/deck_box_millennium_puzzle.png");
    /** Master Duel's add-deck glyph. */
    public static final ResourceLocation ADD_DECK = gui("hub/add_deck.png");
    /** Regulation ring; the word inside remains normal rendered text. */
    public static final ResourceLocation STANDARD_BADGE = gui("hub/standard_badge.png");

    public static ResourceLocation deckBox(
        de.cas_ual_ty.dueldimension.duel.profile.DeckBoxStyle style)
    {
        return switch(style == null
            ? de.cas_ual_ty.dueldimension.duel.profile.DeckBoxStyle.BLUE : style)
        {
            case RED -> DECK_BOX_RED;
            case PURPLE -> DECK_BOX_PURPLE;
            case VORTEX_OF_MAGIC -> DECK_BOX_VORTEX_OF_MAGIC;
            case BLUE_EYES_MAX -> DECK_BOX_BLUE_EYES_MAX;
            case DARK_MAGICAL_BLAST -> DECK_BOX_DARK_MAGICAL_BLAST;
            case RAGE_OF_DEEP_BLUE -> DECK_BOX_RAGE_OF_DEEP_BLUE;
            case CYBER_KAISER -> DECK_BOX_CYBER_KAISER;
            case HEIR_TO_THE_SHIRANUI_STYLE -> DECK_BOX_HEIR_TO_THE_SHIRANUI_STYLE;
            case EMERGENCE_OF_THE_MONARCHS -> DECK_BOX_EMERGENCE_OF_THE_MONARCHS;
            case GEM_KNIGHTS_RESOLUTION -> DECK_BOX_GEM_KNIGHTS_RESOLUTION;
            case BURNING_SPIRITS -> DECK_BOX_BURNING_SPIRITS;
            case XYZ_BLACK -> DECK_BOX_XYZ_BLACK;
            case CARD_CASE_WIND -> DECK_BOX_CARD_CASE_WIND;
            case LINK_BLUE -> DECK_BOX_LINK_BLUE;
            case RE_CONTRACT_UNIVERSE -> DECK_BOX_RE_CONTRACT_UNIVERSE;
            case MAGICIAN_OF_PENDULUM -> DECK_BOX_MAGICIAN_OF_PENDULUM;
            case RAGE_OF_CIPHER -> DECK_BOX_RAGE_OF_CIPHER;
            case CYBERNETIC_SUCCESSOR -> DECK_BOX_CYBERNETIC_SUCCESSOR;
            case GROWING_DIGITAL_BUG -> DECK_BOX_GROWING_DIGITAL_BUG;
            case ROAR_OF_THE_GLADIATOR_BEASTS -> DECK_BOX_ROAR_OF_THE_GLADIATOR_BEASTS;
            case BEING_WHO_SEES_THE_END_OF_THE_WORLD -> DECK_BOX_BEING_WHO_SEES_THE_END_OF_THE_WORLD;
            case DRAGONMAID_TO_ORDER -> DECK_BOX_DRAGONMAID_TO_ORDER;
            case SPELLBOOK_OF_PROPHECY -> DECK_BOX_SPELLBOOK_OF_PROPHECY;
            case IMMORTAL_GLORY -> DECK_BOX_IMMORTAL_GLORY;
            case SPIRAL_SPEAR_STRIKE -> DECK_BOX_SPIRAL_SPEAR_STRIKE;
            case BLACKWING_S_PRIDE -> DECK_BOX_BLACKWING_S_PRIDE;
            case HIDDEN_ARTS_OF_SHADOWS -> DECK_BOX_HIDDEN_ARTS_OF_SHADOWS;
            case SWORD_OF_SOULS -> DECK_BOX_SWORD_OF_SOULS;
            case ORIGIN_OF_THE_GALAXY -> DECK_BOX_ORIGIN_OF_THE_GALAXY;
            case HEROES_UNION -> DECK_BOX_HEROES_UNION;
            case BLAZE_OF_ALBAZ -> DECK_BOX_BLAZE_OF_ALBAZ;
            case CRIMSON_POWERFORCE -> DECK_BOX_CRIMSON_POWERFORCE;
            case REUNION_OF_RAIDERS -> DECK_BOX_REUNION_OF_RAIDERS;
            case GIGANTIC_SPARKLE -> DECK_BOX_GIGANTIC_SPARKLE;
            case ZERO_TO_FUTURE -> DECK_BOX_ZERO_TO_FUTURE;
            case DUELIST_CARD_CASE_BLUE -> DECK_BOX_DUELIST_CARD_CASE_BLUE;
            case CARD_CASE_LIGHT -> DECK_BOX_CARD_CASE_LIGHT;
            case CARD_CASE_DARK -> DECK_BOX_CARD_CASE_DARK;
            case CARD_CASE_EARTH -> DECK_BOX_CARD_CASE_EARTH;
            case CARD_CASE_WATER -> DECK_BOX_CARD_CASE_WATER;
            case CARD_CASE_FIRE -> DECK_BOX_CARD_CASE_FIRE;
            case GOLD_PRIDE -> DECK_BOX_GOLD_PRIDE;
            case CASE_2024_CARD_CASE -> DECK_BOX_CASE_2024_CARD_CASE;
            case PRESIDENT_S_BRIEFCASE -> DECK_BOX_PRESIDENT_S_BRIEFCASE;
            case MAGICIANS_OF_BONDS_AND_UNITY -> DECK_BOX_MAGICIANS_OF_BONDS_AND_UNITY;
            case KING_S_SARCOPHAGUS -> DECK_BOX_KING_S_SARCOPHAGUS;
            case SNAKE_PATTERN -> DECK_BOX_SNAKE_PATTERN;
            case HALLO_WEEN -> DECK_BOX_HALLO_WEEN;
            case LIVE_TWIN -> DECK_BOX_LIVE_TWIN;
            case DRAGON_OF_PRIDE_AND_SOUL -> DECK_BOX_DRAGON_OF_PRIDE_AND_SOUL;
            case SKY_STRIKER_ACE_RAYE -> DECK_BOX_SKY_STRIKER_ACE_RAYE;
            case SKY_STRIKER_ACE_ROZE -> DECK_BOX_SKY_STRIKER_ACE_ROZE;
            case ABYSSAL_LAND -> DECK_BOX_ABYSSAL_LAND;
            case ORCUST -> DECK_BOX_ORCUST;
            case YUM_YUM_YUMMYS -> DECK_BOX_YUM_YUM_YUMMYS;
            case DIABELLSTAR_THE_BLACK_WITCH -> DECK_BOX_DIABELLSTAR_THE_BLACK_WITCH;
            case LABRYNTH -> DECK_BOX_LABRYNTH;
            case A_CASE_FOR_K9 -> DECK_BOX_A_CASE_FOR_K9;
            case CLOCK_TOWER_PRISON -> DECK_BOX_CLOCK_TOWER_PRISON;
            case KEWL_TUNE -> DECK_BOX_KEWL_TUNE;
            case ELFNOTE -> DECK_BOX_ELFNOTE;
            case DRAGON_RAVINE -> DECK_BOX_DRAGON_RAVINE;
            case EXOSISTER -> DECK_BOX_EXOSISTER;
            case WHITE_BLUE -> DECK_BOX_WHITE_BLUE;
            case THE_MILLENNIUM_PUZZLE -> DECK_BOX_MILLENNIUM_PUZZLE;
            case BLUE -> DECK_PLACEHOLDER;
        };
    }

    /** Section header for the editor's grids. */
    public static final ResourceLocation HEADER = gui("indexed/header.png");
    /**
     * The three section name plates: MAIN, EXTRA and SIDE.
     * <p>
     * Art rather than text. The words never change, so by CLAUDE.md's rule they
     * are not the font's business -- only the count beside them is. Each is
     * {@link #PART_LABEL_H} tall and drawn at its own natural width, which
     * {@link #partLabelWidth} carries because the words are different lengths.
     * <p>
     * Generated by {@code tools/make_deck_part_labels.py}. Edit that rather than
     * the PNGs; it is also where the pixel letterforms live.
     */
    public static final ResourceLocation LABEL_MAIN = gui("deckeditor/label_main.png");
    public static final ResourceLocation LABEL_EXTRA = gui("deckeditor/label_extra.png");
    public static final ResourceLocation LABEL_SIDE = gui("deckeditor/label_side.png");

    /** How tall every section plate is, matching the editor's header band. */
    public static final int PART_LABEL_H = 12;

    /**
     * A section's plate, by the NAME of the part it heads.
     * <p>
     * The name and not the ordinal. This class stays free of {@code DeckList}
     * either way -- it is the texture table, and knows about art -- but an
     * ordinal would silently hand EXTRA's plate to SIDE the day someone
     * reordered the enum, and a wrong label is the kind of bug that survives a
     * screenshot.
     */
    public static ResourceLocation partLabel(String part)
    {
        return switch(part)
        {
            case "EXTRA" -> LABEL_EXTRA;
            case "SIDE" -> LABEL_SIDE;
            default -> LABEL_MAIN;
        };
    }

    /**
     * That plate's width, in the same GUI units it is drawn at.
     * <p>
     * Hardcoded from the generator's own arithmetic rather than read off the
     * texture: the size is wanted during layout, and a texture is not resolved
     * until it is drawn. tools/make_deck_part_labels.py prints the sizes it
     * wrote, which is what these are checked against.
     */
    public static int partLabelWidth(String part)
    {
        return switch(part)
        {
            case "EXTRA" -> 40;
            case "SIDE" -> 34;
            default -> 34;
        };
    }
    /** The dark band the open deck's name sits in, above the grids. */
    public static final ResourceLocation TITLE_RIBBON = gui("indexed/title_ribbon.png");
    /** Marks a favourited card, drawn in the corner of its icon. */
    public static final ResourceLocation STAR = gui("deckeditor/star.png");
    /**
     * Marks a card that has more than one artwork, drawn in the corner of its
     * icon. Shares that corner with {@link #STAR}, which moves aside for it.
     */
    public static final ResourceLocation ALT_ART = gui("deckeditor/alt_art.png");
    /** The recessed search field the trunk is filtered with. */
    public static final ResourceLocation SEARCH_FIELD = gui("indexed/search_field.png");
    /** Filter chip; three rows, the third being lit rather than disabled. */
    public static final ResourceLocation CHIP = gui("indexed/chip.png");
    /** Two tiles: track then thumb. */
    public static final ResourceLocation SCROLLBAR = gui("indexed/scrollbar.png");

    /** Hue around, saturation outward; the picker samples it directly. */
    public static final ResourceLocation COLOUR_WHEEL = gui("settings/colour_wheel.png");
    /** The brightness the wheel does not carry. */
    public static final ResourceLocation VALUE_SLIDER = gui("settings/value_slider.png");
    /** The ring marking the chosen point. */
    public static final ResourceLocation PICKER_CURSOR = gui("settings/picker_cursor.png");

    /**
     * The neutral mat. Carries the mat's lightness and none of its hue, so
     * multiplying it by a chosen colour gives that colour rather than a blend.
     */
    public static final ResourceLocation CUSTOM_MAT =
        ResourceLocation.fromNamespaceAndPath(DuelDimension.MOD_ID, "textures/duel/mats/custom.png");

    private HubTextures()
    {
    }
}
