"""Generate mc1211's access widener from the jar, rather than by hand.

WHY GENERATED. An access widener is a list of names and JVM descriptors with no
compiler behind it: a typo does not fail the build, it fails the game at launch
with "could not find method". There are twenty-odd entries here and every one is
a chance to mistype `Lnet/minecraft/client/renderer/RenderStateShard$WriteMask
StateShard;`. So the descriptors are read out of the jar the module compiles
against, and the only hand-written part is the list of MEMBER NAMES -- which is
short, readable, and fails loudly here if one is wrong.

WHAT IT IS FOR. Drawing a monster so that only its nearest surface is shaded:
one pass writing depth and no colour, a second writing colour and no depth with
the depth test set to EQUAL. Neither render type exists in vanilla, and building
one needs `RenderType.create` (private) plus the state shards (protected).

mc262 widens `RenderType.create` for its own reason already, so this is the same
mechanism on both platforms rather than a new idea on one.

Run:  python tools/gen_accesswidener.py
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'mc1211', 'src', 'main', 'resources', 'dueldimension.accesswidener')

JAVAP = r'C:\Program Files\Java\jdk-25.0.2\bin\javap.exe'
JAR = (r'C:\Users\Admin\.gradle\caches\fabric-loom\minecraftMaven\net\minecraft'
    r'\minecraft-clientonly\1.21.1-loom.mappings.1_21_1.layered+hash.2198-v2'
    r'\minecraft-clientonly-1.21.1-loom.mappings.1_21_1.layered+hash.2198-v2.jar')

RENDER_TYPE = 'net/minecraft/client/renderer/RenderType'
SHARD = 'net/minecraft/client/renderer/RenderStateShard'
STATE = RENDER_TYPE + '$CompositeState'
BUILDER = STATE + '$CompositeStateBuilder'

#: Classes that have to be reachable at all before anything in them can be.
CLASSES = [STATE, BUILDER]

#: (owner, member) for methods. The descriptor is looked up.
METHODS = [
    # Seven arguments: the overload that takes affectsCrumbling and sortOnUpload.
    (RENDER_TYPE, 'create'),
    (STATE, 'builder'),
    (BUILDER, 'setShaderState'),
    (BUILDER, 'setTextureState'),
    (BUILDER, 'setTransparencyState'),
    (BUILDER, 'setDepthTestState'),
    (BUILDER, 'setWriteMaskState'),
    (BUILDER, 'setCullState'),
    (BUILDER, 'setLightmapState'),
    (BUILDER, 'setOverlayState'),
    (BUILDER, 'createCompositeState'),
    (SHARD + '$TextureStateShard', '<init>'),
]

#: (owner, field). Everything the two render types are made of.
FIELDS = [
    (SHARD, 'RENDERTYPE_ENTITY_CUTOUT_SHADER'),
    (SHARD, 'RENDERTYPE_ENTITY_TRANSLUCENT_SHADER'),
    (SHARD, 'NO_TRANSPARENCY'),
    (SHARD, 'TRANSLUCENT_TRANSPARENCY'),
    (SHARD, 'LEQUAL_DEPTH_TEST'),
    (SHARD, 'EQUAL_DEPTH_TEST'),
    (SHARD, 'COLOR_WRITE'),
    (SHARD, 'DEPTH_WRITE'),
    (SHARD, 'CULL'),
    (SHARD, 'LIGHTMAP'),
    (SHARD, 'OVERLAY'),
]


def members(owner):
    """{(name, descriptor)} and {name: [descriptors]} for a class, from javap."""
    text = subprocess.run([JAVAP, '-p', '-s', '-cp', JAR, owner.replace('/', '.')],
        capture_output=True, text=True, check=True).stdout
    out = {}
    name = None
    for line in text.splitlines():
        line = line.strip()
        if line.startswith('descriptor: '):
            if name:
                out.setdefault(name, []).append(line[len('descriptor: '):])
            continue
        # `... setShaderState(...);` or `... FIELD_NAME;` or a constructor.
        match = re.search(r'([\w$<>]+)\s*\(', line)
        if match:
            name = match.group(1)
            # javap prints a constructor as the class's own simple name,
            # nested classes included: RenderStateShard$TextureStateShard(...).
            if name == owner.split('/')[-1]:
                name = '<init>'
        else:
            match = re.search(r'(\w+);\s*$', line)
            name = match.group(1) if match else None
    return out


def main():
    lines = [
        'accessWidener\tv2\tnamed',
        '',
        '# GENERATED by tools/gen_accesswidener.py. Do not hand-edit: the',
        '# descriptors are read out of the Minecraft jar so that a typo fails',
        '# there rather than at launch. Add a member NAME to that script instead.',
        '#',
        '# All of this is for one thing: drawing a monster so that only its',
        '# nearest surface is shaded. One pass writes depth and no colour, a',
        '# second writes colour and no depth with the depth test set to EQUAL, so',
        '# exactly one fragment per pixel survives and a half-transparent',
        '# creature stops showing its own far side through its near side.',
        '#',
        '# Neither render type exists in vanilla and RenderType.create is private,',
        '# which is what all of this opens. mc262 widens the same method for its',
        '# own reason, so this is one mechanism across both platforms.',
        '',
    ]

    for owner in CLASSES:
        lines.append(f'accessible\tclass\t{owner}')
    lines.append('')

    cache = {}
    for owner, member in METHODS:
        cache.setdefault(owner, members(owner))
        found = cache[owner].get(member)
        if not found:
            sys.exit(f'no method {owner}.{member} -- name wrong?')
        # `create` has two overloads; the seven-argument one is the one wanted.
        if member == 'create':
            found = [d for d in found if d.count(';') >= 3 and 'ZZ' in d]
        for descriptor in found:
            lines.append(f'accessible\tmethod\t{owner}\t{member}\t{descriptor}')
    lines.append('')

    for owner, field in FIELDS:
        cache.setdefault(owner, members(owner))
        found = cache[owner].get(field)
        if not found:
            sys.exit(f'no field {owner}.{field} -- name wrong?')
        lines.append(f'accessible\tfield\t{owner}\t{field}\t{found[0]}')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'{OUT}: {sum(1 for l in lines if l.startswith("accessible"))} entries')


if __name__ == '__main__':
    main()
