"""Finds the largest set of ported files that actually compiles, and pins it.

The port has 348 files on disk and none of them building, which is a bad place
to work from: there is no green state, so nothing can regress and no change can
be shown to have helped. Every edit is judged by whether a number went down.

This restores the feedback loop. It compiles, excludes whatever errored,
compiles again, and repeats until `mc1211` is green -- then writes the exclusion
list into `mc1211/port-excludes.txt`, which the build reads. What is IN the build
compiles and stays compiling; what is out is the work remaining, named file by
file.

    python tools/port_green.py

From then on the loop is: pick a file off the exclude list, fix it, delete its
line, build. A red build means the fix was wrong, which is the whole point.

Exclusion cascades and that is intended: a file is excluded either because it
uses a 26.2 API or because it references a file that does. Both are "not ported
yet", and distinguishing them is what `port_blockers` is for -- not this.
"""
import io
import os
import re
import subprocess
import sys

GRADLE = os.path.abspath('gradlew25.cmd')
ROOT = 'mc1211/src/main/java'
EXCLUDES = 'mc1211/port-excludes.txt'
ERROR_AT = re.compile(r'^(.*\.java):\d+: error:', re.M)
MAX_ROUNDS = 40


def write_excludes(paths):
    with io.open(EXCLUDES, 'w', encoding='utf-8', newline='\n') as out:
        out.write('# Ported to 1.21.1 but NOT YET COMPILING. Generated by\n'
                  '# tools/port_green.py; mc1211/build.gradle reads it.\n'
                  '#\n'
                  '# A file is here either because it uses a 26.2 API with no 1.21.1\n'
                  '# equivalent, or because it references a file that does. Fix one,\n'
                  '# delete its line, build. A red build means the fix was wrong.\n'
                  '#\n'
                  '# %d file(s) remaining.\n' % len(paths))
        for path in sorted(paths):
            out.write(path + '\n')


def compile_target():
    done = subprocess.run([GRADLE, '-p', 'mc1211', 'compileJava'],
                          capture_output=True, text=True, errors='replace')
    return done.returncode, done.stdout + done.stderr


def failing(output):
    out = set()
    for path in ERROR_AT.findall(output):
        path = path.strip().replace('\\', '/')
        marker = '/' + ROOT + '/'
        if marker in path:
            out.add(path.split(marker, 1)[1])
    return out


def main():
    excluded = set()
    if os.path.exists(EXCLUDES):
        for line in io.open(EXCLUDES, encoding='utf-8'):
            line = line.strip()
            if line and not line.startswith('#'):
                excluded.add(line)
        print('starting from %d already excluded' % len(excluded))

    for round_number in range(1, MAX_ROUNDS + 1):
        write_excludes(excluded)
        code, output = compile_target()
        if code == 0:
            total = sum(1 for _, _, fs in os.walk(ROOT) for f in fs if f.endswith('.java'))
            print('\nmc1211 compiles with %d of %d file(s) in the build.'
                  % (total - len(excluded), total))
            print('%d excluded -- see %s' % (len(excluded), EXCLUDES))
            return 0

        bad = failing(output)
        fresh = bad - excluded
        if not fresh:
            print('\nRound %d found nothing new to exclude, and it still does not '
                  'compile. That is a build problem, not a port problem:\n' % round_number)
            for line in output.splitlines():
                if 'error:' in line:
                    print('   ' + line.strip()[:150])
            return 1

        excluded |= fresh
        print('round %d: excluded %d more (total %d)' % (round_number, len(fresh), len(excluded)))

    print('gave up after %d rounds' % MAX_ROUNDS)
    return 1


if __name__ == '__main__':
    sys.exit(main())
